/**
 * Edge function bundler.
 *
 * The whole point of `submit-lesson` is that it runs the SAME grading code as the
 * client. That means it imports from `packages/engines`, which a deployed Deno
 * function cannot reach — so this script vendors those modules into the deploy
 * payload rather than letting anyone copy-paste them (a copy is exactly the drift
 * the architecture exists to prevent).
 *
 * Two rewrites are needed:
 *   1. `../../../packages/engines/src/x` → `./_engines/x`
 *   2. `./y.js` → `./y.ts`   — TypeScript's NodeNext style, which Deno cannot resolve
 *
 * Run: pnpm edge:build   (or import buildFunction from a deploy script)
 */

import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const enginesSrc = join(here, '..', '..', 'packages', 'engines', 'src')
const packsDir = join(here, '..', '..', 'packages', 'content', 'packs', 'geography')

export type DeployFile = { name: string; content: string }

/** Engine modules the function actually needs. Keep this list minimal. */
const ENGINE_MODULES = [
  'shared/index.ts',
  'learning/types.ts',
  'learning/fsrs.ts',
  'xp/balance.ts',
  'grading/index.ts',
  'time/index.ts',
]

/**
 * `grading` imports AnsweredItem from `lesson/machine`, which drags in the whole
 * state machine and `content/types` for a single type. Types are erased at
 * runtime, so the bundle substitutes a local declaration instead — 11KB of dead
 * weight removed from every cold start.
 *
 * The shape is asserted against the real one in build.test.ts, so this cannot
 * silently drift from the module it stands in for.
 */
const ANSWERED_ITEM_SHIM = `/** Structural stand-in for lesson/machine.ts — see build.ts. */
export type AnsweredItem = {
  readonly itemId: string
  readonly factId: string
  readonly templateId: string
  readonly chosenOptionId: string | null
  readonly wasCorrect: boolean
  readonly elapsedMs: number
  readonly answeredAt: number
}
`

/**
 * The answer key: fact id → the entity id that is the correct option.
 *
 * Vendored at build time because the server has to decide correctness ITSELF. It used
 * to trust `wasCorrect` off the request body, which meant a modified client could post
 * `wasCorrect: true` for ten fabricated answers and mint XP, coins and mastery. That is
 * the exploit ADR 0006 exists to prevent, and PROJECT.md lists server-authoritative
 * rewards as never waivable.
 *
 * A whole content index is not needed for this. `buildQuestion` always gives the
 * correct option the id of the item's entity, so correctness is one lookup: does the
 * chosen option id equal the entity this fact is about? No RNG replay, no option
 * ordering, no template evaluation.
 *
 * Facts are not in Postgres — they ship in packs — so this is generated rather than
 * queried. It is ~200 entries and regenerates on every `pnpm edge:build`.
 */
function buildAnswerKey(): string {
  const key: Record<string, string> = {}

  for (const file of readdirSync(packsDir)) {
    if (!file.startsWith('facts.') || !file.endsWith('.json')) continue
    const pack = JSON.parse(readFileSync(join(packsDir, file), 'utf8')) as {
      items?: { id: string; entity: string }[]
    }
    for (const fact of pack.items ?? []) {
      if (typeof fact.id === 'string' && typeof fact.entity === 'string') {
        key[fact.id] = fact.entity
      }
    }
  }

  return `/**
 * Generated by supabase/functions/build.ts — do not edit.
 *
 * fact id → the entity id that is the correct answer. See buildAnswerKey().
 */
export const ANSWER_BY_FACT: Record<string, string> = ${JSON.stringify(key, null, 2)}
`
}

/** Deno resolves real paths; TS's `.js` extension convention has to go. */
const rewriteImports = (code: string): string =>
  code.replace(/(from\s+['"])(\.[^'"]*?)\.js(['"])/g, '$1$2.ts$3')

export function buildFunction(name: string): DeployFile[] {
  const entrypoint = readFileSync(join(here, name, 'index.ts'), 'utf8')

  const files: DeployFile[] = [
    {
      name: 'index.ts',
      content: rewriteImports(
        entrypoint.replace(/\.\.\/\.\.\/\.\.\/packages\/engines\/src\//g, './_engines/'),
      ),
    },
  ]

  for (const module of ENGINE_MODULES) {
    const source = readFileSync(join(enginesSrc, module), 'utf8')
    files.push({ name: `_engines/${module}`, content: rewriteImports(source) })
  }

  files.push({ name: '_engines/lesson/machine.ts', content: ANSWERED_ITEM_SHIM })
  files.push({ name: '_content/answers.ts', content: buildAnswerKey() })

  // Deno needs to know these are ES modules with the same strictness we use.
  files.push({
    name: 'deno.json',
    content: JSON.stringify(
      { compilerOptions: { strict: true, lib: ['deno.window', 'esnext'] } },
      null,
      2,
    ),
  })

  return files
}

/**
 * The bundle files that have no on-disk counterpart, and therefore have to be written.
 *
 * Everything else this script produces is a REWRITE of something already in the repo:
 * `index.ts` with its import paths remapped, the engine modules copied under
 * `_engines/`. Writing those would clobber the sources they came from. `_content/` is
 * different — it is derived from the content packs and exists nowhere until it is
 * generated.
 *
 * That distinction was invisible for as long as this script only ever printed. The
 * bundle was assembled in memory, verified, described, and dropped on the floor — so
 * `supabase/functions/submit-lesson/index.ts` sat on disk importing
 * `./_content/answers.ts`, a file no checkout has ever contained. The first CI run that
 * got as far as `supabase start` said so:
 *
 *   failed to read file: open supabase/functions/submit-lesson/_content/answers.ts:
 *   no such file or directory
 *
 * and `pnpm edge:deploy` would have failed identically, from any machine, at any point
 * in this project's history. Nothing caught it because `build.test.ts` asserts things
 * about the in-memory bundle, which was always correct — it was just never anywhere.
 *
 * Generated, not committed, for the reason `.gitignore` gives for tokens and keys: the
 * answer key is a projection of the fact packs, so a committed copy is a copy that can
 * disagree with them. `pnpm generate` runs this on install, which is what makes a fresh
 * clone able to start the local stack.
 */
const GENERATED = ['_content/answers.ts']

/** Write the generated-only files into the function directory. Returns what it wrote. */
export function writeGenerated(name: string): string[] {
  const built = buildFunction(name)
  const written: string[] = []

  for (const file of built) {
    if (!GENERATED.includes(file.name)) continue
    const target = join(here, name, file.name)
    mkdirSync(dirname(target), { recursive: true })
    writeFileSync(target, file.content)
    written.push(relative(join(here, '..', '..'), target))
  }

  return written
}

/**
 * Assert the bundle is self-contained before anyone deploys it.
 *
 * Checks imports specifically, not raw text — doc comments legitimately mention
 * `packages/engines`, and a substring search would flag those forever.
 */
export function verifyBundle(files: DeployFile[]): string[] {
  const problems: string[] = []
  for (const file of files) {
    for (const match of file.content.matchAll(/from\s+['"]([^'"]+)['"]/g)) {
      const spec = match[1]!
      if (spec.startsWith('.') && !spec.endsWith('.ts')) {
        problems.push(`${file.name}: unresolvable import "${spec}"`)
      }
      if (spec.includes('packages/engines')) {
        problems.push(`${file.name}: escaped the bundle via "${spec}"`)
      }
    }
  }
  return problems
}

// `tsx supabase/functions/build.ts submit-lesson` — verify the bundle, and write the
// generated half of it so the local stack and `functions deploy` can read it.
if (process.argv[2]) {
  const name = process.argv[2]
  const built = buildFunction(name)
  const problems = verifyBundle(built)
  console.log(`Built "${name}" — ${built.length} files:`)
  for (const f of built) console.log(`  ${f.name.padEnd(28)} ${f.content.length} bytes`)
  if (problems.length) {
    console.error('\n✗ bundle is not self-contained:')
    for (const p of problems) console.error('  ' + p)
    process.exit(1)
  }
  console.log('\n✓ bundle is self-contained')

  for (const path of writeGenerated(name)) console.log(`  wrote ${path}`)
}
