/**
 * Decoding and signature-checking, against a real certificate chain.
 *
 * The fixtures are genuine ES256 certificates and a genuine JWS, generated by
 * `scripts/make-jws-fixtures.cjs`. That matters: everything else in this repo about
 * store notifications is tested with plain objects, and a verifier tested only against
 * objects shaped like what we *hoped* DER looks like has never parsed a certificate.
 */

import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { chainFrom, decodeJws, verifySignature } from './apple-jws.js'
import { verifyChain, verifyClaims } from './store-verification.js'

const fixtures = JSON.parse(
  readFileSync(join(import.meta.dirname, '__fixtures__', 'jws.json'), 'utf8'),
) as {
  rootFingerprint: string
  x5c: string[]
  evilX5c: string[]
  valid: string
  wrongSigner: string
  tampered: string
}

/**
 * A moment inside the fixtures' own validity window.
 *
 * NOT a hardcoded date: the certificates are generated by a script, so their `validFrom`
 * is whenever that ran. A fixed NOW made every chain assertion fail with "certificate 0
 * is not yet valid" the first time these ran on a machine an hour behind the generator.
 */
const NOW = chainFrom(
  (JSON.parse(readFileSync(join(import.meta.dirname, '__fixtures__', 'jws.json'), 'utf8')) as { x5c: string[] }).x5c,
)![0]!.validFrom + 86_400_000

describe('decoding', () => {
  it('splits a real compact JWS into its three parts', () => {
    const jws = decodeJws(fixtures.valid)!
    expect(jws.header.alg).toBe('ES256')
    expect(jws.header.x5c).toHaveLength(3)
    expect(jws.payload['notificationType']).toBe('DID_RENEW')
  })

  it('returns null rather than throwing on anything malformed', () => {
    // The input is from a stranger. "Not a JWS" is an ordinary Tuesday.
    expect(decodeJws('')).toBeNull()
    expect(decodeJws('one.two')).toBeNull()
    expect(decodeJws('not.base64url.at all')).toBeNull()
    expect(decodeJws('eyJhIjoxfQ.bm90LWpzb24.sig')).toBeNull()
  })
})

describe('the certificate chain, parsed from real DER', () => {
  it('builds certificates whose links verify against each other', () => {
    const chain = chainFrom(fixtures.x5c)!
    expect(chain).toHaveLength(3)
    expect(
      verifyChain(chain, { rootFingerprint: fixtures.rootFingerprint, now: NOW }),
    ).toBeNull()
  })

  it('reads real validity windows off the certificates', () => {
    const chain = chainFrom(fixtures.x5c)!
    for (const c of chain) {
      expect(Number.isNaN(c.validFrom)).toBe(false)
      expect(c.validTo).toBeGreaterThan(c.validFrom)
    }
  })

  it('rejects a genuine, internally consistent chain from the wrong root', () => {
    // Every signature in this chain is real. Only the pin catches it — which is the
    // whole reason the root is pinned rather than merely required to be a valid CA.
    const chain = chainFrom(fixtures.evilX5c)!
    expect(
      verifyChain(chain, { rootFingerprint: fixtures.rootFingerprint, now: NOW }),
    ).toMatch(/pinned root/)
  })

  it('returns null for a chain that will not parse', () => {
    expect(chainFrom(['not-a-certificate'])).toBeNull()
    expect(chainFrom([])).toBeNull()
    expect(chainFrom(undefined)).toBeNull()
  })
})

describe('the signature', () => {
  it('accepts a payload actually signed by the leaf', () => {
    const jws = decodeJws(fixtures.valid)!
    expect(verifySignature(jws, fixtures.x5c[0]!)).toBe(true)
  })

  it('rejects a payload edited after signing', () => {
    // The "decode and trust" failure, made concrete: the header and signature are
    // untouched and genuine, and the bundleId now says com.attacker.app.
    const jws = decodeJws(fixtures.tampered)!
    expect((jws.payload['data'] as { bundleId: string }).bundleId).toBe('com.attacker.app')
    expect(verifySignature(jws, fixtures.x5c[0]!)).toBe(false)
  })

  it('rejects a signature made by the wrong key in the same chain', () => {
    // Signed by the intermediate rather than the leaf. The chain is perfect; the
    // signature is not the leaf's, and the leaf is what the chain vouches for.
    const jws = decodeJws(fixtures.wrongSigner)!
    expect(verifySignature(jws, fixtures.x5c[0]!)).toBe(false)
  })

  it('refuses any algorithm but ES256, including none', () => {
    // Letting the sender pick how their signature is checked is the `alg: none` family
    // of bugs. The header is theirs; the algorithm is ours.
    const jws = decodeJws(fixtures.valid)!
    for (const alg of ['none', 'HS256', 'RS256', undefined]) {
      expect(verifySignature({ ...jws, header: { ...jws.header, alg } }, fixtures.x5c[0]!)).toBe(false)
    }
  })
})

describe('all three layers together, on a real notification', () => {
  it('accepts a genuine notification for this app', () => {
    const jws = decodeJws(fixtures.valid)!
    const chain = chainFrom(jws.header.x5c)!

    expect(verifyChain(chain, { rootFingerprint: fixtures.rootFingerprint, now: NOW })).toBeNull()
    expect(verifySignature(jws, jws.header.x5c![0]!)).toBe(true)

    const data = jws.payload['data'] as { bundleId: string; environment: string }
    expect(
      verifyClaims(
        {
          bundleId: data.bundleId,
          environment: data.environment,
          signedDate: jws.payload['signedDate'] as number,
        },
        {
          bundleId: 'com.wrexist.worldquest',
          environment: 'production',
          now: jws.payload['signedDate'] as number,
          maxAgeMs: 3 * 86_400_000,
        },
      ),
    ).toBeNull()
  })

  it('stops a tampered notification at the signature, before the claims are read', () => {
    // Order matters: the edited bundleId would ALSO be caught by verifyClaims, but only
    // because this fixture edits a field policy happens to check. Signature first means
    // it does not matter which field was edited.
    const jws = decodeJws(fixtures.tampered)!
    expect(verifySignature(jws, jws.header.x5c![0]!)).toBe(false)
  })
})
