/**
 * The four checks, in the order that makes them mean something.
 *
 * `apple-jws.ts` can tell you whether a signature is good. `store-verification.ts` can
 * tell you whether a payload is about our app and recent enough to act on.
 * `apple-notification.ts` can read the payload. None of them is a decision. This is where
 * they are composed, and composition order is the entire security property:
 *
 *   1. It parses as a JWS at all.
 *   2. The certificate chain terminates at the pinned root, every link verified, every
 *      window checked.
 *   3. The leaf's key actually signed these bytes.
 *   4. Only now are the claims read — and the first one asked is whether this
 *      notification is about *us*.
 *
 * Reordering 3 and 4 is the bug this whole subsystem exists to avoid. Reading claims from
 * an unverified payload and then verifying is not "the same checks in a different order";
 * it is a handler that has already branched on attacker-controlled data.
 *
 * ## The nested JWS is signed separately, so it is verified separately
 *
 * `data.signedTransactionInfo` is its own compact JWS with its own `x5c`. It carries
 * `originalTransactionId` — the value that decides *which user's subscription this is* —
 * so accepting it because the envelope around it was signed would mean the one field
 * that selects an account is the one field nobody checked.
 *
 * ## What cannot be tested without an Apple developer account
 *
 * The value of `rootFingerprint`. Everything else here runs against a real ES256 chain
 * generated by `scripts/make-jws-fixtures.cjs`, including the forgeries. The pin is a
 * fact about Apple's CA, and this repo's rule is to mark a fact we cannot source rather
 * than invent one — so it is configuration, read from the environment, and the endpoint
 * refuses to start without it.
 *
 * Spec: docs/systems/monetization.md
 */

import { chainFrom, decodeJws, verifySignature } from './apple-jws.js'
import { verifyChain, verifyClaims } from './store-verification.js'
import {
  parseAppleNotification,
  type AppleDecodedPayload,
  type AppleTransactionInfo,
  type ParsedAppleNotification,
} from './apple-notification.js'

export type AppleVerifyPolicy = {
  /** SHA-256 of Apple's root CA, `node:crypto` format. Configuration, never a literal. */
  readonly rootFingerprint: string
  /** Ours. The check that separates "Apple sent this" from "Apple sent this about us". */
  readonly bundleId: string
  readonly environment: 'sandbox' | 'production'
  readonly now: number
  /** The replay window. Wide enough for Apple's three-day retry schedule, and finite. */
  readonly maxAgeMs: number
}

/**
 * Verified, or a reason — and the reason never leaves our logs.
 *
 * A discriminated result rather than `null` because the two audiences differ: the sender
 * gets 401 and nothing else, while whoever is debugging a missing subscription at 2am
 * needs to know it was the bundle id.
 */
export type VerifyResult =
  | { readonly ok: true; readonly value: ParsedAppleNotification; readonly payload: unknown }
  | { readonly ok: false; readonly reason: string }

/** Verify one compact JWS against the pinned root, and return its payload. */
function verifyEnvelope(
  compact: string,
  policy: AppleVerifyPolicy,
  label: string,
): { ok: true; payload: Record<string, unknown> } | { ok: false; reason: string } {
  const jws = decodeJws(compact)
  if (jws === null) return { ok: false, reason: `${label}: not a JWS` }

  const chain = chainFrom(jws.header.x5c)
  if (chain === null) return { ok: false, reason: `${label}: no usable x5c chain` }

  const chainProblem = verifyChain(chain, {
    rootFingerprint: policy.rootFingerprint,
    now: policy.now,
  })
  if (chainProblem !== null) return { ok: false, reason: `${label}: ${chainProblem}` }

  // Only after the chain is trusted does the leaf's key mean anything: verifying against
  // a leaf from an unvalidated chain proves the sender signed their own certificate.
  if (!verifySignature(jws, jws.header.x5c![0]!)) {
    return { ok: false, reason: `${label}: signature does not verify` }
  }

  return { ok: true, payload: jws.payload }
}

export function verifyAppleNotification(raw: string, policy: AppleVerifyPolicy): VerifyResult {
  const outer = verifyEnvelope(raw, policy, 'notification')
  if (!outer.ok) return { ok: false, reason: outer.reason }

  const payload = outer.payload as AppleDecodedPayload

  // The audience check. Apple signs notifications for every app on the store, so
  // everything above this line is satisfied by a genuine notification about somebody
  // else's app — which anyone with a developer account can obtain and post here.
  const claimProblem = verifyClaims(
    {
      bundleId: typeof payload.data?.bundleId === 'string' ? payload.data.bundleId : undefined,
      environment:
        typeof payload.data?.environment === 'string' ? payload.data.environment : undefined,
      signedDate: typeof payload.signedDate === 'number' ? payload.signedDate : undefined,
    },
    {
      bundleId: policy.bundleId,
      environment: policy.environment,
      now: policy.now,
      maxAgeMs: policy.maxAgeMs,
    },
  )
  if (claimProblem !== null) return { ok: false, reason: `claims: ${claimProblem}` }

  const signedTransaction = payload.data?.signedTransactionInfo
  if (typeof signedTransaction !== 'string') {
    return { ok: false, reason: 'no signedTransactionInfo' }
  }

  // Independently signed, therefore independently verified. This is where
  // `originalTransactionId` comes from, and that is the field that picks the account.
  const inner = verifyEnvelope(signedTransaction, policy, 'transaction')
  if (!inner.ok) return { ok: false, reason: inner.reason }

  const parsed = parseAppleNotification(payload, inner.payload as AppleTransactionInfo)
  if (parsed === null) return { ok: false, reason: 'payload is missing a required field' }

  // The raw JWS goes to the append-only log rather than our reading of it. A dispute is
  // answered by what arrived, not by what we understood at the time.
  return { ok: true, value: parsed, payload: { signedPayload: raw } }
}
