/**
 * Writes `src/catalogue.generated.ts` — the strings, and only the strings, that a phone
 * needs at runtime.
 *
 * ## Why this exists
 *
 * Half the locale catalogue is `__note`: translator context, written for a human deciding
 * how to render a sentence in Swedish, and never rendered to anybody. `index.ts` has
 * always known that — `toBundle` skips every key ending in `__note` while building its
 * resources — but it was skipping them at *runtime*, from JSON that had already been
 * `import`ed. A string discarded on the first frame is still a string Hermes parsed to get
 * there.
 *
 * Measured, on the compiled bytecode rather than on the source, because this repo has been
 * wrong about that before (see the Hermes string-dedup note in `scripts/bundle-native.cjs`):
 * stripping the notes moved iOS from **4.60 MB to 4.52** and Android from 4.60 to 4.51.
 * 73.9 KB of the 145.6 KB catalogue is notes, and unlike the licence strings that turned
 * out to cost nothing, every note is distinct prose — so there is nothing for the string
 * table to fold together and the bytes are real.
 *
 * That is roughly the 0.1 MB of headroom every raise in `bundle-native.cjs` has asked for,
 * recovered without a sixth budget number. The header of that file refuses one for
 * application code, which is the correct call and is why this script exists instead.
 *
 * ## What it does NOT change
 *
 * The notes stay exactly where they are, in `locales/`, next to the strings they describe.
 * They are required — `pnpm i18n:check` fails a short or ambiguous string without one, and
 * `packages/i18n/CLAUDE.md` says so — and they are what a translator actually opens. This
 * only stops shipping them to a device that cannot read them.
 *
 * The namespace prefix comes off here too, for the same reason it used to come off at
 * startup: the files store the full `namespace:key` because that is what a developer greps
 * for, and i18next wants the namespace as a bundle boundary. Doing it at build time means
 * the app no longer walks 629 keys before its first frame.
 *
 * ## Keeping it honest
 *
 * Generated, never edited, and regenerated by `pnpm i18n:types` — which `pnpm generate`
 * runs, which `pnpm verify` runs first of all. So a string added to a locale file and not
 * regenerated here cannot survive a verify, locally or in CI. Same contract as `keys.ts`,
 * from the same locale files, deliberately: two generated artefacts with two different
 * freshness stories is how one of them goes stale.
 *
 * Run: pnpm i18n:types
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const localesDir = join(root, 'locales')
const outFile = join(root, 'src', 'catalogue.generated.ts')

/**
 * The locales that ship in the binary.
 *
 * Read from disk rather than imported from `index.ts`, which imports the file this script
 * writes — a cycle that resolves at runtime and confuses every tool that reads it
 * statically. The pseudo-locale is excluded because it is generated, gitignored and never
 * shipped; `pnpm i18n:pseudo` builds it and `index.ts` loads it separately.
 */
const PSEUDO = 'en-XA'
const locales = readdirSync(localesDir, { withFileTypes: true })
  .filter((entry) => entry.isDirectory() && entry.name !== PSEUDO)
  .map((entry) => entry.name)
  .sort()

/**
 * All three counters are **UTF-8 bytes of the key and value text**, via
 * `Buffer.byteLength` rather than `String.length`.
 *
 * `.length` is UTF-16 code units, which is not a size in bytes and is not even the same
 * shape as one: `ö` is one unit and two bytes, and every Swedish note in this catalogue
 * has several. Reported as "KB" it is simply a wrong number, and a wrong number in a note
 * about bundle weight is worse than none — `scripts/bundle-native.cjs` exists because this
 * repo has twice been misled by a size it did not actually measure.
 *
 * What it does NOT count is the JSON syntax around the strings — the quotes, colons,
 * commas and braces. That is deliberate: what this script removes from the bundle is the
 * note text, and the punctuation would only be double-counted against the generated module
 * that replaces it. The only number that decides anything is the compiled `.hbc`, which
 * `pnpm bundle:native` measures and neither of these counters tries to predict.
 */
const utf8 = (value: string): number => Buffer.byteLength(value, 'utf8')

let noteBytes = 0
let stringBytes = 0
let keyCount = 0

const catalogue: Record<string, Record<string, Record<string, string>>> = {}

for (const locale of locales) {
  const dir = join(localesDir, locale)
  const bundles: Record<string, Record<string, string>> = {}

  for (const file of readdirSync(dir).filter((name) => name.endsWith('.json')).sort()) {
    const namespace = file.replace(/\.json$/, '')
    const raw = JSON.parse(readFileSync(join(dir, file), 'utf8')) as Record<string, string>
    const prefix = `${namespace}:`
    const bundle: Record<string, string> = {}

    for (const [key, value] of Object.entries(raw)) {
      const size = utf8(key) + utf8(value)
      if (key.endsWith('__note')) {
        noteBytes += size
        continue
      }
      stringBytes += size
      keyCount++
      bundle[key.startsWith(prefix) ? key.slice(prefix.length) : key] = value
    }

    bundles[namespace] = bundle
  }

  catalogue[locale] = bundles
}

const source = `/**
 * GENERATED by \`pnpm i18n:types\` from \`packages/i18n/locales/\`. Do not edit.
 *
 * The shipped half of the catalogue: every string, no \`__note\`, namespace prefixes already
 * stripped. See \`scripts/build-catalogue.ts\` for why the notes do not come along.
 */

/**
 * Annotated rather than \`as const\`, deliberately. The literal type of 1,258 keys across
 * two locales is enormous and buys nothing: what is typed against is \`TranslationKey\` in
 * \`keys.ts\`, generated from the same files, and i18next receives this as plain data.
 */
export const CATALOGUE: Record<string, Record<string, Record<string, string>>> =
${JSON.stringify(catalogue, null, 2)}
`

writeFileSync(outFile, source)

const kb = (bytes: number): string => `${(bytes / 1024).toFixed(1)} KB`

console.log(`\nRuntime catalogue\n`)
console.log(`  locales     ${locales.length}  (${locales.join(', ')})`)
console.log(`  keys        ${keyCount}`)
// The unit is named in the output, so a number copied out of here into a commit message
// or a budget note carries its own definition. See `utf8` above.
console.log(`  shipped     ${kb(stringBytes)} of key + value text (UTF-8)`)
console.log(`  left behind ${kb(noteBytes)} of translator notes`)
console.log(`  catalogue   ${kb(stringBytes + noteBytes)} — notes are ${Math.round((noteBytes / (stringBytes + noteBytes)) * 100)}% of it`)
console.log(`\n✓ wrote src/catalogue.generated.ts`)
