// Generated by scripts/build-adventure-art.cjs. Decorative illustrations only.
import a0 from '../../assets/art/adventure/africa.webp'
import a1 from '../../assets/art/adventure/antarctica.webp'
import a2 from '../../assets/art/adventure/asia.webp'
import a3 from '../../assets/art/adventure/europe.webp'
import a4 from '../../assets/art/atlas-globe/welcome.webp'
import a5 from '../../assets/art/adventure/island.webp'
import a6 from '../../assets/art/adventure/north-america.webp'
import a7 from '../../assets/art/adventure/oceania.webp'
import a8 from '../../assets/art/adventure/passport.webp'
import a9 from '../../assets/art/adventure/south-america.webp'
import a10 from '../../assets/art/explorer-chest/closed.webp'
export const ADVENTURE_ART = {
  'africa': a0,
  'antarctica': a1,
  'asia': a2,
  'europe': a3,
  'explorer': a4,
  'island': a5,
  'north-america': a6,
  'oceania': a7,
  'passport': a8,
  'south-america': a9,
  'treasure': a10,
} as const
