// Generated by scripts/build-playful-art.cjs. Legacy slots resolve to their current runtime artwork; editable SVG masters remain in docs/design/assets/playful.
import a0 from '../../assets/art/atlas-globe/thinking.webp'
import a1 from '../../assets/art/atlas-globe/celebrate.webp'
import a2 from '../../assets/art/atlas-globe/encouraging.webp'
import a3 from '../../assets/art/atlas-globe/welcome.webp'
import a4 from '../../assets/art/atlas-globe/resting.webp'
import a5 from '../../assets/art/atlas-globe/thinking.webp'
import a6 from '../../assets/art/atlas-globe/welcome.webp'
import a7 from '../../assets/art/atlas-globe/welcome.webp'
import a8 from '../../assets/art/atlas-globe/celebrate.webp'
import a9 from '../../assets/art/atlas-globe/welcome.webp'
import a10 from '../../assets/art/atlas-globe/thinking.webp'
import a11 from '../../assets/art/atlas-globe/celebrate.webp'
import a12 from '../../assets/art/explorer-chest/closed.webp'
import a13 from '../../assets/art/atlas-globe/resting.webp'
import a14 from '../../assets/art/atlas-globe/thinking.webp'
import a15 from '../../assets/art/states/hearts-empty.webp'
import a16 from '../../assets/art/atlas-globe/sleepy.webp'
import a17 from '../../assets/art/playful/celebration--burst.webp'
import a18 from '../../assets/art/playful/celebration--rays.webp'
import a19 from '../../assets/art/playful/achievements--glyph-capitals.webp'
import a20 from '../../assets/art/playful/achievements--glyph-collections.webp'
import a21 from '../../assets/art/playful/achievements--glyph-consistency.webp'
import a22 from '../../assets/art/playful/achievements--glyph-countries.webp'
import a23 from '../../assets/art/playful/achievements--glyph-events.webp'
import a24 from '../../assets/art/playful/achievements--glyph-exploration.webp'
import a25 from '../../assets/art/playful/achievements--glyph-flags.webp'
import a26 from '../../assets/art/playful/achievements--glyph-hidden.webp'
import a27 from '../../assets/art/playful/achievements--glyph-landmarks.webp'
import a28 from '../../assets/art/playful/achievements--glyph-legendary.webp'
import a29 from '../../assets/art/playful/achievements--glyph-perfect.webp'
import a30 from '../../assets/art/playful/achievements--glyph-premium.webp'
import a31 from '../../assets/art/playful/achievements--glyph-social.webp'
import a32 from '../../assets/art/playful/achievements--tier-bronze.webp'
import a33 from '../../assets/art/playful/achievements--tier-gold.webp'
import a34 from '../../assets/art/playful/achievements--tier-legendary.webp'
import a35 from '../../assets/art/playful/achievements--tier-platinum.webp'
import a36 from '../../assets/art/playful/achievements--tier-silver.webp'
import a37 from '../../assets/art/playful/avatars--avatar-01.webp'
import a38 from '../../assets/art/playful/avatars--avatar-02.webp'
import a39 from '../../assets/art/playful/avatars--avatar-03.webp'
import a40 from '../../assets/art/playful/avatars--avatar-04.webp'
import a41 from '../../assets/art/playful/avatars--avatar-05.webp'
import a42 from '../../assets/art/playful/avatars--avatar-06.webp'
import a43 from '../../assets/art/playful/avatars--avatar-07.webp'
import a44 from '../../assets/art/playful/avatars--avatar-08.webp'
import a45 from '../../assets/art/playful/avatars--avatar-09.webp'
import a46 from '../../assets/art/playful/avatars--avatar-10.webp'
import a47 from '../../assets/art/playful/avatars--avatar-11.webp'
import a48 from '../../assets/art/playful/avatars--avatar-12.webp'
import a49 from '../../assets/art/playful/continents--AF.webp'
import a50 from '../../assets/art/playful/continents--AN.webp'
import a51 from '../../assets/art/playful/continents--AS.webp'
import a52 from '../../assets/art/playful/continents--EU.webp'
import a53 from '../../assets/art/playful/continents--NA.webp'
import a54 from '../../assets/art/playful/continents--OC.webp'
import a55 from '../../assets/art/playful/continents--SA.webp'
import a56 from '../../assets/art/playful/continents-silhouette--AF.webp'
import a57 from '../../assets/art/playful/continents-silhouette--AS.webp'
import a58 from '../../assets/art/playful/continents-silhouette--EU.webp'
import a59 from '../../assets/art/playful/continents-silhouette--NA.webp'
import a60 from '../../assets/art/playful/continents-silhouette--OC.webp'
import a61 from '../../assets/art/playful/continents-silhouette--SA.webp'
import a62 from '../../assets/art/playful/levels--cartographer.webp'
import a63 from '../../assets/art/playful/levels--circumnavigator.webp'
import a64 from '../../assets/art/playful/levels--globetrotter.webp'
import a65 from '../../assets/art/playful/levels--circumnavigator.webp'
import a66 from '../../assets/art/playful/levels--circumnavigator.webp'
import a67 from '../../assets/art/playful/levels--scout.webp'
import a68 from '../../assets/art/playful/levels--trailblazer.webp'
import a69 from '../../assets/art/playful/levels--globetrotter.webp'
import a70 from '../../assets/art/playful/levels--wanderer.webp'
import a71 from '../../assets/art/playful/levels--worldkeeper.webp'
import a72 from '../../assets/art/rewards/globe.webp'
import a73 from '../../assets/art/playful/achievements--glyph-consistency.webp'
import a74 from '../../assets/art/playful/rewards--streak-freeze.webp'
export type ArtModule = number | string
export const ART_BY_NAME = {
  'atlas/broken-compass': a0,
  'atlas/celebrate': a1,
  'atlas/encouraging': a2,
  'atlas/explorer': a3,
  'atlas/resting': a4,
  'atlas/thinking': a5,
  'atlas/waving-back': a6,
  'atlas/welcome': a7,
  'onboarding/conquer': a8,
  'onboarding/explore': a9,
  'onboarding/learn': a10,
  'states/empty-caught-up': a11,
  'states/empty-collection': a12,
  'states/empty-profile': a13,
  'states/error-generic': a14,
  'states/hearts-empty': a15,
  'states/offline': a16,
  'celebration/burst': a17,
  'celebration/rays': a18,
  'achievements/glyph-capitals': a19,
  'achievements/glyph-collections': a20,
  'achievements/glyph-consistency': a21,
  'achievements/glyph-countries': a22,
  'achievements/glyph-events': a23,
  'achievements/glyph-exploration': a24,
  'achievements/glyph-flags': a25,
  'achievements/glyph-hidden': a26,
  'achievements/glyph-landmarks': a27,
  'achievements/glyph-legendary': a28,
  'achievements/glyph-perfect': a29,
  'achievements/glyph-premium': a30,
  'achievements/glyph-social': a31,
  'achievements/tier-bronze': a32,
  'achievements/tier-gold': a33,
  'achievements/tier-legendary': a34,
  'achievements/tier-platinum': a35,
  'achievements/tier-silver': a36,
  'avatars/avatar-01': a37,
  'avatars/avatar-02': a38,
  'avatars/avatar-03': a39,
  'avatars/avatar-04': a40,
  'avatars/avatar-05': a41,
  'avatars/avatar-06': a42,
  'avatars/avatar-07': a43,
  'avatars/avatar-08': a44,
  'avatars/avatar-09': a45,
  'avatars/avatar-10': a46,
  'avatars/avatar-11': a47,
  'avatars/avatar-12': a48,
  'continents/AF': a49,
  'continents/AN': a50,
  'continents/AS': a51,
  'continents/EU': a52,
  'continents/NA': a53,
  'continents/OC': a54,
  'continents/SA': a55,
  'continents-silhouette/AF': a56,
  'continents-silhouette/AS': a57,
  'continents-silhouette/EU': a58,
  'continents-silhouette/NA': a59,
  'continents-silhouette/OC': a60,
  'continents-silhouette/SA': a61,
  'levels/cartographer': a62,
  'levels/circumnavigator': a63,
  'levels/globetrotter': a64,
  'levels/navigator': a65,
  'levels/pathfinder': a66,
  'levels/scout': a67,
  'levels/trailblazer': a68,
  'levels/voyager': a69,
  'levels/wanderer': a70,
  'levels/worldkeeper': a71,
  'rewards/globe': a72,
  'rewards/streak-flame': a73,
  'rewards/streak-freeze': a74,
} as const
export type ArtName = keyof typeof ART_BY_NAME
export type ArtGeometry = { readonly aspect:number; readonly x:number; readonly y:number; readonly w:number; readonly h:number }
const g0 = {"aspect":1,"x":0.04375,"y":0.2046875,"w":0.9125,"h":0.7671875} as const
const g1 = {"aspect":1,"x":0.04375,"y":0.1578125,"w":0.9125,"h":0.8140625} as const
const g2 = {"aspect":1,"x":0.158203125,"y":0.07421875,"w":0.681640625,"h":0.84765625} as const
const g3 = {"aspect":1,"x":0.10546875,"y":0.10546875,"w":0.7890625,"h":0.85546875} as const
const g4 = {"aspect":1,"x":0.01953125,"y":0.01953125,"w":0.9609375,"h":0.98046875} as const
const g5 = {"aspect":1,"x":0,"y":0,"w":1,"h":1} as const
const g6 = {"aspect":1,"x":0.03125,"y":0.03125,"w":0.9375,"h":0.9375} as const
export const ART_GEOMETRY = {
  'atlas/broken-compass': g0,
  'atlas/celebrate': g1,
  'atlas/encouraging': g0,
  'atlas/explorer': g0,
  'atlas/resting': g0,
  'atlas/thinking': g0,
  'atlas/waving-back': g0,
  'atlas/welcome': g0,
  'onboarding/conquer': g1,
  'onboarding/explore': g0,
  'onboarding/learn': g0,
  'states/empty-caught-up': g1,
  'states/empty-collection': {"aspect":1,"x":0.109375,"y":0.2984375,"w":0.7953125,"h":0.6578125},
  'states/empty-profile': g0,
  'states/error-generic': g0,
  'states/hearts-empty': {"aspect":1.5,"x":0.2981770833333333,"y":0.10546875,"w":0.3880208333333333,"h":0.79296875},
  'states/offline': {"aspect":1,"x":0.04375,"y":0.1109375,"w":0.925,"h":0.8609375},
  'celebration/burst': {"aspect":1,"x":0.072265625,"y":0.08203125,"w":0.82421875,"h":0.83984375},
  'celebration/rays': {"aspect":1,"x":0.02734375,"y":0.02734375,"w":0.9453125,"h":0.9453125},
  'achievements/glyph-capitals': {"aspect":1,"x":0.08984375,"y":0.109375,"w":0.8203125,"h":0.80859375},
  'achievements/glyph-collections': {"aspect":1,"x":0.109375,"y":0.1796875,"w":0.78125,"h":0.6953125},
  'achievements/glyph-consistency': g2,
  'achievements/glyph-countries': {"aspect":1,"x":0.15625,"y":0.09765625,"w":0.6875,"h":0.80859375},
  'achievements/glyph-events': {"aspect":1,"x":0.15234375,"y":0.07421875,"w":0.6953125,"h":0.83203125},
  'achievements/glyph-exploration': {"aspect":1,"x":0.12109375,"y":0.11328125,"w":0.7578125,"h":0.765625},
  'achievements/glyph-flags': {"aspect":1,"x":0.212890625,"y":0.099609375,"w":0.630859375,"h":0.80859375},
  'achievements/glyph-hidden': {"aspect":1,"x":0.08203125,"y":0.26171875,"w":0.8359375,"h":0.4765625},
  'achievements/glyph-landmarks': {"aspect":1,"x":0.07421875,"y":0.171875,"w":0.86328125,"h":0.68359375},
  'achievements/glyph-legendary': {"aspect":1,"x":0.13671875,"y":0.1484375,"w":0.7265625,"h":0.69921875},
  'achievements/glyph-perfect': {"aspect":1,"x":0.19140625,"y":0.166015625,"w":0.6171875,"h":0.587890625},
  'achievements/glyph-premium': {"aspect":1,"x":0.18359375,"y":0.158203125,"w":0.6328125,"h":0.6015625},
  'achievements/glyph-social': {"aspect":1,"x":0.1328125,"y":0.19140625,"w":0.734375,"h":0.67578125},
  'achievements/tier-bronze': g3,
  'achievements/tier-gold': g3,
  'achievements/tier-legendary': g3,
  'achievements/tier-platinum': g3,
  'achievements/tier-silver': g3,
  'avatars/avatar-01': g4,
  'avatars/avatar-02': g4,
  'avatars/avatar-03': g4,
  'avatars/avatar-04': g4,
  'avatars/avatar-05': g4,
  'avatars/avatar-06': g4,
  'avatars/avatar-07': g4,
  'avatars/avatar-08': g4,
  'avatars/avatar-09': g4,
  'avatars/avatar-10': g4,
  'avatars/avatar-11': g4,
  'avatars/avatar-12': g4,
  'continents/AF': g5,
  'continents/AN': g5,
  'continents/AS': g5,
  'continents/EU': g5,
  'continents/NA': g5,
  'continents/OC': g5,
  'continents/SA': g5,
  'continents-silhouette/AF': {"aspect":1,"x":0.26953125,"y":0.25,"w":0.4296875,"h":0.462890625},
  'continents-silhouette/AS': {"aspect":1,"x":0.205078125,"y":0.203125,"w":0.533203125,"h":0.517578125},
  'continents-silhouette/EU': {"aspect":1,"x":0.271484375,"y":0.150390625,"w":0.42578125,"h":0.5390625},
  'continents-silhouette/NA': {"aspect":1,"x":0.201171875,"y":0.216796875,"w":0.529296875,"h":0.470703125},
  'continents-silhouette/OC': {"aspect":1,"x":0.31640625,"y":0.31640625,"w":0.462890625,"h":0.35546875},
  'continents-silhouette/SA': {"aspect":1,"x":0.357421875,"y":0.28125,"w":0.30859375,"h":0.435546875},
  'levels/cartographer': g6,
  'levels/circumnavigator': g6,
  'levels/globetrotter': g6,
  'levels/navigator': g6,
  'levels/pathfinder': g6,
  'levels/scout': g6,
  'levels/trailblazer': g6,
  'levels/voyager': g6,
  'levels/wanderer': g6,
  'levels/worldkeeper': g6,
  'rewards/globe': {"aspect":1.5,"x":0.14453125,"y":0,"w":0.7109375,"h":1},
  'rewards/streak-flame': g2,
  'rewards/streak-freeze': {"aspect":1,"x":0.1171875,"y":0.125,"w":0.765625,"h":0.734375},
} as const satisfies Readonly<Record<ArtName,ArtGeometry>>
