/**
 * GENERATED by `pnpm build:art` — do not edit.
 *
 * Illustrations derived from the masters in docs/design/assets. See scripts/build-art.cjs
 * for why they are WebP, why they are 768px, and why this file exists at all.
 */

import atlasWelcome from '../../assets/art/atlas/welcome.webp'
import atlasCelebrate from '../../assets/art/atlas/celebrate.webp'
import atlasThinking from '../../assets/art/atlas/thinking.webp'
import atlasEncouraging from '../../assets/art/atlas/encouraging.webp'
import atlasWavingBack from '../../assets/art/atlas/waving-back.webp'
import atlasBrokenCompass from '../../assets/art/atlas/broken-compass.webp'
import atlasResting from '../../assets/art/atlas/resting.webp'
import onboardingExplore from '../../assets/art/onboarding/explore.webp'
import onboardingLearn from '../../assets/art/onboarding/learn.webp'
import onboardingConquer from '../../assets/art/onboarding/conquer.webp'
import statesEmptyCaughtUp from '../../assets/art/states/empty-caught-up.webp'
import statesEmptyNoFriends from '../../assets/art/states/empty-no-friends.webp'
import statesEmptyProfile from '../../assets/art/states/empty-profile.webp'
import statesEmptyCollection from '../../assets/art/states/empty-collection.webp'
import statesErrorGeneric from '../../assets/art/states/error-generic.webp'
import statesOffline from '../../assets/art/states/offline.webp'
import statesHeartsEmpty from '../../assets/art/states/hearts-empty.webp'
import celebrationBurst from '../../assets/art/celebration/burst.webp'
import celebrationRays from '../../assets/art/celebration/rays.webp'

/** Metro hands back a numeric handle; Vite hands back a URL. Both are real. */
export type ArtModule = number | string

/** Art name → the bundled illustration. */
export const ART_BY_NAME = {
  'atlas/welcome': atlasWelcome,
  'atlas/celebrate': atlasCelebrate,
  'atlas/thinking': atlasThinking,
  'atlas/encouraging': atlasEncouraging,
  'atlas/waving-back': atlasWavingBack,
  'atlas/broken-compass': atlasBrokenCompass,
  'atlas/resting': atlasResting,
  'onboarding/explore': onboardingExplore,
  'onboarding/learn': onboardingLearn,
  'onboarding/conquer': onboardingConquer,
  'states/empty-caught-up': statesEmptyCaughtUp,
  'states/empty-no-friends': statesEmptyNoFriends,
  'states/empty-profile': statesEmptyProfile,
  'states/empty-collection': statesEmptyCollection,
  'states/error-generic': statesErrorGeneric,
  'states/offline': statesOffline,
  'states/hearts-empty': statesHeartsEmpty,
  'celebration/burst': celebrationBurst,
  'celebration/rays': celebrationRays,
} as const satisfies Readonly<Record<string, ArtModule>>

/** Every illustration this build ships. */
export type ArtName = keyof typeof ART_BY_NAME
