/**
 * GENERATED by `pnpm build:art` — do not edit.
 *
 * Illustrations derived from the masters in docs/design/assets. See scripts/build-art.cjs
 * for why they are WebP, why they are 768px, and why this file exists at all.
 */

import atlasBrokenCompass from '../../assets/art/atlas/broken-compass.webp'
import atlasCelebrate from '../../assets/art/atlas/celebrate.webp'
import atlasEncouraging from '../../assets/art/atlas/encouraging.webp'
import atlasExplorer from '../../assets/art/atlas/explorer.webp'
import atlasResting from '../../assets/art/atlas/resting.webp'
import atlasThinking from '../../assets/art/atlas/thinking.webp'
import atlasWavingBack from '../../assets/art/atlas/waving-back.webp'
import atlasWelcome from '../../assets/art/atlas/welcome.webp'
import onboardingConquer from '../../assets/art/onboarding/conquer.webp'
import onboardingExplore from '../../assets/art/onboarding/explore.webp'
import onboardingLearn from '../../assets/art/onboarding/learn.webp'
import statesEmptyCaughtUp from '../../assets/art/states/empty-caught-up.webp'
import statesEmptyCollection from '../../assets/art/states/empty-collection.webp'
import statesEmptyProfile from '../../assets/art/states/empty-profile.webp'
import statesErrorGeneric from '../../assets/art/states/error-generic.webp'
import statesHeartsEmpty from '../../assets/art/states/hearts-empty.webp'
import statesOffline from '../../assets/art/states/offline.webp'
import celebrationBurst from '../../assets/art/celebration/burst.webp'
import celebrationRays from '../../assets/art/celebration/rays.webp'
import achievementsGlyphCapitals from '../../assets/art/achievements/glyph-capitals.webp'
import achievementsGlyphCollections from '../../assets/art/achievements/glyph-collections.webp'
import achievementsGlyphConsistency from '../../assets/art/achievements/glyph-consistency.webp'
import achievementsGlyphCountries from '../../assets/art/achievements/glyph-countries.webp'
import achievementsGlyphEvents from '../../assets/art/achievements/glyph-events.webp'
import achievementsGlyphExploration from '../../assets/art/achievements/glyph-exploration.webp'
import achievementsGlyphFlags from '../../assets/art/achievements/glyph-flags.webp'
import achievementsGlyphHidden from '../../assets/art/achievements/glyph-hidden.webp'
import achievementsGlyphLandmarks from '../../assets/art/achievements/glyph-landmarks.webp'
import achievementsGlyphLegendary from '../../assets/art/achievements/glyph-legendary.webp'
import achievementsGlyphPerfect from '../../assets/art/achievements/glyph-perfect.webp'
import achievementsGlyphPremium from '../../assets/art/achievements/glyph-premium.webp'
import achievementsGlyphSocial from '../../assets/art/achievements/glyph-social.webp'
import achievementsTierBronze from '../../assets/art/achievements/tier-bronze.webp'
import achievementsTierGold from '../../assets/art/achievements/tier-gold.webp'
import achievementsTierLegendary from '../../assets/art/achievements/tier-legendary.webp'
import achievementsTierPlatinum from '../../assets/art/achievements/tier-platinum.webp'
import achievementsTierSilver from '../../assets/art/achievements/tier-silver.webp'
import avatarsAvatar01 from '../../assets/art/avatars/avatar-01.webp'
import avatarsAvatar02 from '../../assets/art/avatars/avatar-02.webp'
import avatarsAvatar03 from '../../assets/art/avatars/avatar-03.webp'
import avatarsAvatar04 from '../../assets/art/avatars/avatar-04.webp'
import avatarsAvatar05 from '../../assets/art/avatars/avatar-05.webp'
import avatarsAvatar06 from '../../assets/art/avatars/avatar-06.webp'
import avatarsAvatar07 from '../../assets/art/avatars/avatar-07.webp'
import avatarsAvatar08 from '../../assets/art/avatars/avatar-08.webp'
import avatarsAvatar09 from '../../assets/art/avatars/avatar-09.webp'
import avatarsAvatar10 from '../../assets/art/avatars/avatar-10.webp'
import avatarsAvatar11 from '../../assets/art/avatars/avatar-11.webp'
import avatarsAvatar12 from '../../assets/art/avatars/avatar-12.webp'
import continentsAF from '../../assets/art/continents/AF.webp'
import continentsAN from '../../assets/art/continents/AN.webp'
import continentsAS from '../../assets/art/continents/AS.webp'
import continentsEU from '../../assets/art/continents/EU.webp'
import continentsNA from '../../assets/art/continents/NA.webp'
import continentsOC from '../../assets/art/continents/OC.webp'
import continentsSA from '../../assets/art/continents/SA.webp'
import continentsSilhouetteAF from '../../assets/art/continents-silhouette/AF.webp'
import continentsSilhouetteAS from '../../assets/art/continents-silhouette/AS.webp'
import continentsSilhouetteEU from '../../assets/art/continents-silhouette/EU.webp'
import continentsSilhouetteNA from '../../assets/art/continents-silhouette/NA.webp'
import continentsSilhouetteOC from '../../assets/art/continents-silhouette/OC.webp'
import continentsSilhouetteSA from '../../assets/art/continents-silhouette/SA.webp'
import levelsCartographer from '../../assets/art/levels/cartographer.webp'
import levelsCircumnavigator from '../../assets/art/levels/circumnavigator.webp'
import levelsGlobetrotter from '../../assets/art/levels/globetrotter.webp'
import levelsNavigator from '../../assets/art/levels/navigator.webp'
import levelsPathfinder from '../../assets/art/levels/pathfinder.webp'
import levelsScout from '../../assets/art/levels/scout.webp'
import levelsTrailblazer from '../../assets/art/levels/trailblazer.webp'
import levelsVoyager from '../../assets/art/levels/voyager.webp'
import levelsWanderer from '../../assets/art/levels/wanderer.webp'
import levelsWorldkeeper from '../../assets/art/levels/worldkeeper.webp'
import rewardsGlobe from '../../assets/art/rewards/globe.webp'
import rewardsStreakFlame from '../../assets/art/rewards/streak-flame.webp'
import rewardsStreakFreeze from '../../assets/art/rewards/streak-freeze.webp'

/** Metro hands back a numeric handle; Vite hands back a URL. Both are real. */
export type ArtModule = number | string

/** Art name → the bundled illustration. */
export const ART_BY_NAME = {
  'atlas/broken-compass': atlasBrokenCompass,
  'atlas/celebrate': atlasCelebrate,
  'atlas/encouraging': atlasEncouraging,
  'atlas/explorer': atlasExplorer,
  'atlas/resting': atlasResting,
  'atlas/thinking': atlasThinking,
  'atlas/waving-back': atlasWavingBack,
  'atlas/welcome': atlasWelcome,
  'onboarding/conquer': onboardingConquer,
  'onboarding/explore': onboardingExplore,
  'onboarding/learn': onboardingLearn,
  'states/empty-caught-up': statesEmptyCaughtUp,
  'states/empty-collection': statesEmptyCollection,
  'states/empty-profile': statesEmptyProfile,
  'states/error-generic': statesErrorGeneric,
  'states/hearts-empty': statesHeartsEmpty,
  'states/offline': statesOffline,
  'celebration/burst': celebrationBurst,
  'celebration/rays': celebrationRays,
  'achievements/glyph-capitals': achievementsGlyphCapitals,
  'achievements/glyph-collections': achievementsGlyphCollections,
  'achievements/glyph-consistency': achievementsGlyphConsistency,
  'achievements/glyph-countries': achievementsGlyphCountries,
  'achievements/glyph-events': achievementsGlyphEvents,
  'achievements/glyph-exploration': achievementsGlyphExploration,
  'achievements/glyph-flags': achievementsGlyphFlags,
  'achievements/glyph-hidden': achievementsGlyphHidden,
  'achievements/glyph-landmarks': achievementsGlyphLandmarks,
  'achievements/glyph-legendary': achievementsGlyphLegendary,
  'achievements/glyph-perfect': achievementsGlyphPerfect,
  'achievements/glyph-premium': achievementsGlyphPremium,
  'achievements/glyph-social': achievementsGlyphSocial,
  'achievements/tier-bronze': achievementsTierBronze,
  'achievements/tier-gold': achievementsTierGold,
  'achievements/tier-legendary': achievementsTierLegendary,
  'achievements/tier-platinum': achievementsTierPlatinum,
  'achievements/tier-silver': achievementsTierSilver,
  'avatars/avatar-01': avatarsAvatar01,
  'avatars/avatar-02': avatarsAvatar02,
  'avatars/avatar-03': avatarsAvatar03,
  'avatars/avatar-04': avatarsAvatar04,
  'avatars/avatar-05': avatarsAvatar05,
  'avatars/avatar-06': avatarsAvatar06,
  'avatars/avatar-07': avatarsAvatar07,
  'avatars/avatar-08': avatarsAvatar08,
  'avatars/avatar-09': avatarsAvatar09,
  'avatars/avatar-10': avatarsAvatar10,
  'avatars/avatar-11': avatarsAvatar11,
  'avatars/avatar-12': avatarsAvatar12,
  'continents/AF': continentsAF,
  'continents/AN': continentsAN,
  'continents/AS': continentsAS,
  'continents/EU': continentsEU,
  'continents/NA': continentsNA,
  'continents/OC': continentsOC,
  'continents/SA': continentsSA,
  'continents-silhouette/AF': continentsSilhouetteAF,
  'continents-silhouette/AS': continentsSilhouetteAS,
  'continents-silhouette/EU': continentsSilhouetteEU,
  'continents-silhouette/NA': continentsSilhouetteNA,
  'continents-silhouette/OC': continentsSilhouetteOC,
  'continents-silhouette/SA': continentsSilhouetteSA,
  'levels/cartographer': levelsCartographer,
  'levels/circumnavigator': levelsCircumnavigator,
  'levels/globetrotter': levelsGlobetrotter,
  'levels/navigator': levelsNavigator,
  'levels/pathfinder': levelsPathfinder,
  'levels/scout': levelsScout,
  'levels/trailblazer': levelsTrailblazer,
  'levels/voyager': levelsVoyager,
  'levels/wanderer': levelsWanderer,
  'levels/worldkeeper': levelsWorldkeeper,
  'rewards/globe': rewardsGlobe,
  'rewards/streak-flame': rewardsStreakFlame,
  'rewards/streak-freeze': rewardsStreakFreeze,
} as const satisfies Readonly<Record<string, ArtModule>>

/** Every illustration this build ships. */
export type ArtName = keyof typeof ART_BY_NAME

/**
 * Where the subject sits inside each illustration, as fractions of the image.
 *
 * `aspect` is width ÷ height; `x`/`y`/`w`/`h` are the opaque content's bounding box.
 * MEASURED off the shipped WebP, so it already accounts for anything the build did to
 * the master. `<Art>` uses it to size the SUBJECT rather than the frame — see the note
 * on `measure()` in scripts/build-art.cjs for why that gap was worth closing.
 */
export type ArtGeometry = {
  readonly aspect: number
  readonly x: number
  readonly y: number
  readonly w: number
  readonly h: number
}

export const ART_GEOMETRY = {
  'atlas/broken-compass': { aspect: 1.5, x: 0.3281, y: 0.0742, w: 0.4128, h: 0.707 },
  'atlas/celebrate': { aspect: 1.5, x: 0.2383, y: 0.1211, w: 0.556, h: 0.709 },
  'atlas/encouraging': { aspect: 1.5, x: 0.3021, y: 0.0645, w: 0.3724, h: 0.6699 },
  'atlas/explorer': { aspect: 1.5, x: 0.1315, y: 0.1055, w: 0.7409, h: 0.8945 },
  'atlas/resting': { aspect: 1, x: 0, y: 0, w: 1, h: 1 },
  'atlas/thinking': { aspect: 1.5, x: 0.3477, y: 0.0977, w: 0.3398, h: 0.6094 },
  'atlas/waving-back': { aspect: 1.5, x: 0.3021, y: 0.0918, w: 0.4648, h: 0.5879 },
  'atlas/welcome': { aspect: 1.5, x: 0.3034, y: 0.0508, w: 0.4271, h: 0.8379 },
  'onboarding/conquer': { aspect: 1.5, x: 0.194, y: 0.2793, w: 0.806, h: 0.7207 },
  'onboarding/explore': { aspect: 1.5, x: 0, y: 0, w: 1, h: 1 },
  'onboarding/learn': { aspect: 1.5, x: 0.3151, y: 0.3574, w: 0.4076, h: 0.4883 },
  'states/empty-caught-up': { aspect: 1.5, x: 0.3711, y: 0.293, w: 0.2773, h: 0.5625 },
  'states/empty-collection': { aspect: 1.5, x: 0.2461, y: 0.0703, w: 0.4818, h: 0.7598 },
  'states/empty-profile': { aspect: 1.5, x: 0, y: 0, w: 1, h: 1 },
  'states/error-generic': { aspect: 1.5, x: 0, y: 0.3496, w: 1, h: 0.5488 },
  'states/hearts-empty': { aspect: 1.5, x: 0.332, y: 0.1055, w: 0.3346, h: 0.7754 },
  'states/offline': { aspect: 1.5, x: 0, y: 0.3477, w: 1, h: 0.6523 },
  'celebration/burst': { aspect: 1.5, x: 0.1719, y: 0.0449, w: 0.6641, h: 0.8652 },
  'celebration/rays': { aspect: 1.5, x: 0.3047, y: 0.1816, w: 0.3815, h: 0.5078 },
  'achievements/glyph-capitals': { aspect: 1, x: 0.2331, y: 0.2109, w: 0.5339, h: 0.5521 },
  'achievements/glyph-collections': { aspect: 1, x: 0.2513, y: 0.2331, w: 0.4961, h: 0.4922 },
  'achievements/glyph-consistency': { aspect: 1, x: 0.2565, y: 0.2383, w: 0.487, h: 0.5208 },
  'achievements/glyph-countries': { aspect: 1, x: 0.2448, y: 0.2292, w: 0.5026, h: 0.5547 },
  'achievements/glyph-events': { aspect: 1, x: 0.2513, y: 0.1732, w: 0.5339, h: 0.5716 },
  'achievements/glyph-exploration': { aspect: 1, x: 0.2188, y: 0.2057, w: 0.5612, h: 0.5924 },
  'achievements/glyph-flags': { aspect: 1, x: 0.3346, y: 0.2565, w: 0.4115, h: 0.4557 },
  'achievements/glyph-hidden': { aspect: 1, x: 0.349, y: 0.2578, w: 0.3164, h: 0.4857 },
  'achievements/glyph-landmarks': { aspect: 1, x: 0.2318, y: 0.2422, w: 0.5365, h: 0.5078 },
  'achievements/glyph-legendary': { aspect: 1, x: 0.2344, y: 0.2917, w: 0.5299, h: 0.4128 },
  'achievements/glyph-perfect': { aspect: 1, x: 0.2682, y: 0.2383, w: 0.4896, h: 0.5078 },
  'achievements/glyph-premium': { aspect: 1, x: 0.2708, y: 0.2852, w: 0.4544, h: 0.4453 },
  'achievements/glyph-social': { aspect: 1, x: 0.2292, y: 0.2591, w: 0.5534, h: 0.3945 },
  'achievements/tier-bronze': { aspect: 1, x: 0.1875, y: 0.1766, w: 0.6406, h: 0.675 },
  'achievements/tier-gold': { aspect: 1, x: 0.2135, y: 0.1992, w: 0.5729, h: 0.5964 },
  'achievements/tier-legendary': { aspect: 1, x: 0.2044, y: 0.1901, w: 0.5898, h: 0.6419 },
  'achievements/tier-platinum': { aspect: 1, x: 0.2122, y: 0.1992, w: 0.5768, h: 0.6016 },
  'achievements/tier-silver': { aspect: 1, x: 0.2148, y: 0.1979, w: 0.5703, h: 0.612 },
  'avatars/avatar-01': { aspect: 1.5, x: 0.2135, y: 0.0488, w: 0.5182, h: 0.9219 },
  'avatars/avatar-02': { aspect: 1.5, x: 0.2109, y: 0.0703, w: 0.5091, h: 0.9297 },
  'avatars/avatar-03': { aspect: 1.5, x: 0.2005, y: 0.0684, w: 0.5599, h: 0.9316 },
  'avatars/avatar-04': { aspect: 1.5, x: 0.2083, y: 0.0625, w: 0.5508, h: 0.9375 },
  'avatars/avatar-05': { aspect: 1.5, x: 0.1979, y: 0.0742, w: 0.5651, h: 0.9258 },
  'avatars/avatar-06': { aspect: 1, x: 0.1133, y: 0.0391, w: 0.7188, h: 0.9609 },
  'avatars/avatar-07': { aspect: 1, x: 0.0344, y: 0.0141, w: 0.9125, h: 0.9859 },
  'avatars/avatar-08': { aspect: 1, x: 0.0984, y: 0.0406, w: 0.8156, h: 0.9594 },
  'avatars/avatar-09': { aspect: 1, x: 0.0891, y: 0.0391, w: 0.8344, h: 0.9609 },
  'avatars/avatar-10': { aspect: 1, x: 0.0891, y: 0.0391, w: 0.8313, h: 0.9609 },
  'avatars/avatar-11': { aspect: 1, x: 0.0922, y: 0.0469, w: 0.8313, h: 0.9531 },
  'avatars/avatar-12': { aspect: 1, x: 0.0953, y: 0.05, w: 0.8344, h: 0.95 },
  'continents/AF': { aspect: 1.5, x: 0, y: 0, w: 1, h: 1 },
  'continents/AN': { aspect: 1.5, x: 0, y: 0, w: 1, h: 1 },
  'continents/AS': { aspect: 1.5, x: 0, y: 0, w: 1, h: 1 },
  'continents/EU': { aspect: 1.5, x: 0, y: 0, w: 1, h: 1 },
  'continents/NA': { aspect: 1.5, x: 0, y: 0, w: 1, h: 1 },
  'continents/OC': { aspect: 1.5, x: 0, y: 0, w: 1, h: 1 },
  'continents/SA': { aspect: 1.5, x: 0, y: 0, w: 1, h: 1 },
  'continents-silhouette/AF': { aspect: 1, x: 0.0794, y: 0.0508, w: 0.8177, h: 0.8867 },
  'continents-silhouette/AS': { aspect: 1.5, x: 0.1068, y: 0.0273, w: 0.8255, h: 0.9238 },
  'continents-silhouette/EU': { aspect: 1.5, x: 0.1497, y: 0.0215, w: 0.7031, h: 0.9707 },
  'continents-silhouette/NA': { aspect: 0.8398, x: 0, y: 0, w: 1, h: 1 },
  'continents-silhouette/OC': { aspect: 1.5, x: 0.1263, y: 0.0488, w: 0.7943, h: 0.8867 },
  'continents-silhouette/SA': { aspect: 1, x: 0.1922, y: 0.0313, w: 0.6781, h: 0.9313 },
  'levels/cartographer': { aspect: 1, x: 0.3398, y: 0.3164, w: 0.3372, h: 0.3333 },
  'levels/circumnavigator': { aspect: 1.5, x: 0.3346, y: 0.2676, w: 0.349, h: 0.4395 },
  'levels/globetrotter': { aspect: 1.5, x: 0.3359, y: 0.2012, w: 0.3451, h: 0.5078 },
  'levels/navigator': { aspect: 1, x: 0.3229, y: 0.3073, w: 0.3529, h: 0.3724 },
  'levels/pathfinder': { aspect: 1, x: 0.3268, y: 0.3125, w: 0.3385, h: 0.3385 },
  'levels/scout': { aspect: 1.5, x: 0.2995, y: 0.2324, w: 0.401, h: 0.5137 },
  'levels/trailblazer': { aspect: 1.5, x: 0.3398, y: 0.2363, w: 0.3307, h: 0.4785 },
  'levels/voyager': { aspect: 1, x: 0.3438, y: 0.3216, w: 0.3776, h: 0.3333 },
  'levels/wanderer': { aspect: 1, x: 0.3464, y: 0.2904, w: 0.2682, h: 0.4089 },
  'levels/worldkeeper': { aspect: 1, x: 0.3268, y: 0.3229, w: 0.3685, h: 0.3242 },
  'rewards/globe': { aspect: 1.5, x: 0.1927, y: 0.0371, w: 0.6185, h: 0.9121 },
  'rewards/streak-flame': { aspect: 1, x: 0.2839, y: 0.1289, w: 0.4596, h: 0.7201 },
  'rewards/streak-freeze': { aspect: 1, x: 0.1263, y: 0.1719, w: 0.7201, h: 0.6849 },
} as const satisfies Readonly<Record<ArtName, ArtGeometry>>
