// Generated by scripts/build-atlas-assets.cjs. Original WorldQuest 3D character.
import sheet0 from '../../assets/art/atlas3d/welcome-sheet.webp'
import poster0 from '../../assets/art/atlas3d/welcome-poster.webp'
import pose0 from '../../assets/art/atlas3d/welcome-pose.webp'
import sheet1 from '../../assets/art/atlas3d/celebrate-sheet.webp'
import poster1 from '../../assets/art/atlas3d/celebrate-poster.webp'
import pose1 from '../../assets/art/atlas3d/celebrate-pose.webp'
import sheet2 from '../../assets/art/atlas3d/thinking-sheet.webp'
import poster2 from '../../assets/art/atlas3d/thinking-poster.webp'
import pose2 from '../../assets/art/atlas3d/thinking-pose.webp'
import sheet3 from '../../assets/art/atlas3d/resting-sheet.webp'
import poster3 from '../../assets/art/atlas3d/resting-poster.webp'
import pose3 from '../../assets/art/atlas3d/resting-pose.webp'
import sheet4 from '../../assets/art/atlas3d/encouraging-sheet.webp'
import poster4 from '../../assets/art/atlas3d/encouraging-poster.webp'
import pose4 from '../../assets/art/atlas3d/encouraging-pose.webp'
export const ATLAS_3D = {
  welcome: {sheet:sheet0,poster:poster0,pose:pose0},
  celebrate: {sheet:sheet1,poster:poster1,pose:pose1},
  thinking: {sheet:sheet2,poster:poster2,pose:pose2},
  resting: {sheet:sheet3,poster:poster3,pose:pose3},
  encouraging: {sheet:sheet4,poster:poster4,pose:pose4},
} as const
export const ATLAS_SEQUENCE={frames:48,fps:20,columns:8,rows:6} as const
