// Generated by scripts/build-clay-mascot.cjs. Complete transparent poses, no sprite sheets.
import welcome from '../../assets/art/atlas-clay/welcome.png'
import celebrate from '../../assets/art/atlas-clay/celebrate.png'
import thinking from '../../assets/art/atlas-clay/thinking.png'
import resting from '../../assets/art/atlas-clay/resting.png'

export const ATLAS_CLAY = {
  welcome: welcome,
  celebrate: celebrate,
  thinking: thinking,
  resting: resting,
  encouraging: welcome,
  laughing: celebrate,
  surprised: celebrate,
  proud: welcome,
  sleepy: resting,
  wink: welcome,
} as const

export type AtlasClayMood = keyof typeof ATLAS_CLAY
