// Generated by scripts/build-globe-mascot-art.cjs from Blender renders (scripts/build-globe-mascot.py). Do not edit.
import sheet0 from '../../assets/art/atlas-globe/welcome-sheet.webp'
import still0 from '../../assets/art/atlas-globe/welcome.webp'
import sheet1 from '../../assets/art/atlas-globe/celebrate-sheet.webp'
import still1 from '../../assets/art/atlas-globe/celebrate.webp'
import sheet2 from '../../assets/art/atlas-globe/thinking-sheet.webp'
import still2 from '../../assets/art/atlas-globe/thinking.webp'
import sheet3 from '../../assets/art/atlas-globe/resting-sheet.webp'
import still3 from '../../assets/art/atlas-globe/resting.webp'
import sheet4 from '../../assets/art/atlas-globe/encouraging-sheet.webp'
import still4 from '../../assets/art/atlas-globe/encouraging.webp'
import sheet5 from '../../assets/art/atlas-globe/laughing-sheet.webp'
import still5 from '../../assets/art/atlas-globe/laughing.webp'
import sheet6 from '../../assets/art/atlas-globe/surprised-sheet.webp'
import still6 from '../../assets/art/atlas-globe/surprised.webp'
import sheet7 from '../../assets/art/atlas-globe/proud-sheet.webp'
import still7 from '../../assets/art/atlas-globe/proud.webp'
import sheet8 from '../../assets/art/atlas-globe/sleepy-sheet.webp'
import still8 from '../../assets/art/atlas-globe/sleepy.webp'
import sheet9 from '../../assets/art/atlas-globe/wink-sheet.webp'
import still9 from '../../assets/art/atlas-globe/wink.webp'

export const ATLAS_SEQUENCE = { frames: 36, columns: 6, rows: 6, fps: 18 } as const

export const ATLAS_GLOBE = {
  'welcome': { sheet: sheet0, still: still0 },
  'celebrate': { sheet: sheet1, still: still1 },
  'thinking': { sheet: sheet2, still: still2 },
  'resting': { sheet: sheet3, still: still3 },
  'encouraging': { sheet: sheet4, still: still4 },
  'laughing': { sheet: sheet5, still: still5 },
  'surprised': { sheet: sheet6, still: still6 },
  'proud': { sheet: sheet7, still: still7 },
  'sleepy': { sheet: sheet8, still: still8 },
  'wink': { sheet: sheet9, still: still9 },
} as const

export type AtlasGlobeMood = keyof typeof ATLAS_GLOBE
