// Generated by build-soft-assets.cjs. Original retained expedition assets.
import a0 from '../../assets/art/rewards/globe.webp'
import a1 from '../../assets/art/states/hearts-empty.webp'
export const CLASSIC_ART = {
  'rewards/globe': { asset: a0, geometry: {"aspect":1.5,"x":0.14973958333333334,"y":0,"w":0.7018229166666666,"h":1} },
  'states/hearts-empty': { asset: a1, geometry: {"aspect":1.5,"x":0.30078125,"y":0.10546875,"w":0.3841145833333333,"h":0.791015625} },
} as const
