// Generated by build-soft-assets.cjs. Original retained expedition assets.
import a0 from '../../assets/art/atlas/explorer.webp'
import a1 from '../../assets/art/atlas/welcome.webp'
import a2 from '../../assets/art/atlas/celebrate.webp'
import a3 from '../../assets/art/atlas/encouraging.webp'
import a4 from '../../assets/art/atlas/resting.webp'
import a5 from '../../assets/art/atlas/thinking.webp'
import a6 from '../../assets/art/atlas/waving-back.webp'
import a7 from '../../assets/art/atlas/broken-compass.webp'
import a8 from '../../assets/art/rewards/globe.webp'
import a9 from '../../assets/art/states/hearts-empty.webp'
export const CLASSIC_ART = {
  'atlas/explorer': { asset: a0, geometry: {"aspect":1.5,"x":0.13020833333333334,"y":0.103515625,"w":0.7434895833333334,"h":0.896484375} },
  'atlas/welcome': { asset: a1, geometry: {"aspect":1.5,"x":0.03515625,"y":0.0234375,"w":0.9296875,"h":0.923828125} },
  'atlas/celebrate': { asset: a2, geometry: {"aspect":1.5,"x":0.22265625,"y":0.1171875,"w":0.5755208333333334,"h":0.736328125} },
  'atlas/encouraging': { asset: a3, geometry: {"aspect":1.5,"x":0.3020833333333333,"y":0.0625,"w":0.3736979166666667,"h":0.68359375} },
  'atlas/resting': { asset: a4, geometry: {"aspect":1,"x":0.006510416666666667,"y":0.006510416666666667,"w":0.9869791666666666,"h":0.9869791666666666} },
  'atlas/thinking': { asset: a5, geometry: {"aspect":1.5,"x":0.3307291666666667,"y":0.095703125,"w":0.3580729166666667,"h":0.615234375} },
  'atlas/waving-back': { asset: a6, geometry: {"aspect":1.5,"x":0.30078125,"y":0.08984375,"w":0.4674479166666667,"h":0.61328125} },
  'atlas/broken-compass': { asset: a7, geometry: {"aspect":1.5,"x":0.3268229166666667,"y":0.072265625,"w":0.4153645833333333,"h":0.72265625} },
  'rewards/globe': { asset: a8, geometry: {"aspect":1.5,"x":0.14973958333333334,"y":0,"w":0.7018229166666666,"h":1} },
  'states/hearts-empty': { asset: a9, geometry: {"aspect":1.5,"x":0.30078125,"y":0.10546875,"w":0.3841145833333333,"h":0.791015625} },
} as const
