// Generated by node scripts/build-clay-maps.cjs. Natural Earth + shared GlobeRenderer.
import m0 from '../../assets/geo/clay/AD.webp'
import m1 from '../../assets/geo/clay/AE.webp'
import m2 from '../../assets/geo/clay/AF.webp'
import m3 from '../../assets/geo/clay/AG.webp'
import m4 from '../../assets/geo/clay/AL.webp'
import m5 from '../../assets/geo/clay/AM.webp'
import m6 from '../../assets/geo/clay/AO.webp'
import m7 from '../../assets/geo/clay/AR.webp'
import m8 from '../../assets/geo/clay/AT.webp'
import m9 from '../../assets/geo/clay/AU.webp'
import m10 from '../../assets/geo/clay/AZ.webp'
import m11 from '../../assets/geo/clay/BA.webp'
import m12 from '../../assets/geo/clay/BB.webp'
import m13 from '../../assets/geo/clay/BD.webp'
import m14 from '../../assets/geo/clay/BE.webp'
import m15 from '../../assets/geo/clay/BF.webp'
import m16 from '../../assets/geo/clay/BG.webp'
import m17 from '../../assets/geo/clay/BH.webp'
import m18 from '../../assets/geo/clay/BI.webp'
import m19 from '../../assets/geo/clay/BJ.webp'
import m20 from '../../assets/geo/clay/BN.webp'
import m21 from '../../assets/geo/clay/BO.webp'
import m22 from '../../assets/geo/clay/BR.webp'
import m23 from '../../assets/geo/clay/BS.webp'
import m24 from '../../assets/geo/clay/BT.webp'
import m25 from '../../assets/geo/clay/BW.webp'
import m26 from '../../assets/geo/clay/BY.webp'
import m27 from '../../assets/geo/clay/BZ.webp'
import m28 from '../../assets/geo/clay/CA.webp'
import m29 from '../../assets/geo/clay/CD.webp'
import m30 from '../../assets/geo/clay/CF.webp'
import m31 from '../../assets/geo/clay/CG.webp'
import m32 from '../../assets/geo/clay/CH.webp'
import m33 from '../../assets/geo/clay/CI.webp'
import m34 from '../../assets/geo/clay/CL.webp'
import m35 from '../../assets/geo/clay/CM.webp'
import m36 from '../../assets/geo/clay/CN.webp'
import m37 from '../../assets/geo/clay/CO.webp'
import m38 from '../../assets/geo/clay/CR.webp'
import m39 from '../../assets/geo/clay/CU.webp'
import m40 from '../../assets/geo/clay/CV.webp'
import m41 from '../../assets/geo/clay/CY.webp'
import m42 from '../../assets/geo/clay/CZ.webp'
import m43 from '../../assets/geo/clay/DE.webp'
import m44 from '../../assets/geo/clay/DJ.webp'
import m45 from '../../assets/geo/clay/DK.webp'
import m46 from '../../assets/geo/clay/DM.webp'
import m47 from '../../assets/geo/clay/DO.webp'
import m48 from '../../assets/geo/clay/DZ.webp'
import m49 from '../../assets/geo/clay/EC.webp'
import m50 from '../../assets/geo/clay/EE.webp'
import m51 from '../../assets/geo/clay/EG.webp'
import m52 from '../../assets/geo/clay/ER.webp'
import m53 from '../../assets/geo/clay/ES.webp'
import m54 from '../../assets/geo/clay/ET.webp'
import m55 from '../../assets/geo/clay/FI.webp'
import m56 from '../../assets/geo/clay/FJ.webp'
import m57 from '../../assets/geo/clay/FM.webp'
import m58 from '../../assets/geo/clay/FR.webp'
import m59 from '../../assets/geo/clay/GA.webp'
import m60 from '../../assets/geo/clay/GB.webp'
import m61 from '../../assets/geo/clay/GD.webp'
import m62 from '../../assets/geo/clay/GE.webp'
import m63 from '../../assets/geo/clay/GH.webp'
import m64 from '../../assets/geo/clay/GM.webp'
import m65 from '../../assets/geo/clay/GN.webp'
import m66 from '../../assets/geo/clay/GQ.webp'
import m67 from '../../assets/geo/clay/GR.webp'
import m68 from '../../assets/geo/clay/GT.webp'
import m69 from '../../assets/geo/clay/GW.webp'
import m70 from '../../assets/geo/clay/GY.webp'
import m71 from '../../assets/geo/clay/HN.webp'
import m72 from '../../assets/geo/clay/HR.webp'
import m73 from '../../assets/geo/clay/HT.webp'
import m74 from '../../assets/geo/clay/HU.webp'
import m75 from '../../assets/geo/clay/ID.webp'
import m76 from '../../assets/geo/clay/IE.webp'
import m77 from '../../assets/geo/clay/IL.webp'
import m78 from '../../assets/geo/clay/IN.webp'
import m79 from '../../assets/geo/clay/IQ.webp'
import m80 from '../../assets/geo/clay/IR.webp'
import m81 from '../../assets/geo/clay/IS.webp'
import m82 from '../../assets/geo/clay/IT.webp'
import m83 from '../../assets/geo/clay/JM.webp'
import m84 from '../../assets/geo/clay/JO.webp'
import m85 from '../../assets/geo/clay/JP.webp'
import m86 from '../../assets/geo/clay/KE.webp'
import m87 from '../../assets/geo/clay/KG.webp'
import m88 from '../../assets/geo/clay/KH.webp'
import m89 from '../../assets/geo/clay/KI.webp'
import m90 from '../../assets/geo/clay/KM.webp'
import m91 from '../../assets/geo/clay/KN.webp'
import m92 from '../../assets/geo/clay/KP.webp'
import m93 from '../../assets/geo/clay/KR.webp'
import m94 from '../../assets/geo/clay/KW.webp'
import m95 from '../../assets/geo/clay/KZ.webp'
import m96 from '../../assets/geo/clay/LA.webp'
import m97 from '../../assets/geo/clay/LB.webp'
import m98 from '../../assets/geo/clay/LC.webp'
import m99 from '../../assets/geo/clay/LI.webp'
import m100 from '../../assets/geo/clay/LK.webp'
import m101 from '../../assets/geo/clay/LR.webp'
import m102 from '../../assets/geo/clay/LS.webp'
import m103 from '../../assets/geo/clay/LT.webp'
import m104 from '../../assets/geo/clay/LU.webp'
import m105 from '../../assets/geo/clay/LV.webp'
import m106 from '../../assets/geo/clay/LY.webp'
import m107 from '../../assets/geo/clay/MA.webp'
import m108 from '../../assets/geo/clay/MC.webp'
import m109 from '../../assets/geo/clay/MD.webp'
import m110 from '../../assets/geo/clay/ME.webp'
import m111 from '../../assets/geo/clay/MG.webp'
import m112 from '../../assets/geo/clay/MH.webp'
import m113 from '../../assets/geo/clay/MK.webp'
import m114 from '../../assets/geo/clay/ML.webp'
import m115 from '../../assets/geo/clay/MM.webp'
import m116 from '../../assets/geo/clay/MN.webp'
import m117 from '../../assets/geo/clay/MR.webp'
import m118 from '../../assets/geo/clay/MT.webp'
import m119 from '../../assets/geo/clay/MU.webp'
import m120 from '../../assets/geo/clay/MV.webp'
import m121 from '../../assets/geo/clay/MW.webp'
import m122 from '../../assets/geo/clay/MX.webp'
import m123 from '../../assets/geo/clay/MY.webp'
import m124 from '../../assets/geo/clay/MZ.webp'
import m125 from '../../assets/geo/clay/NA.webp'
import m126 from '../../assets/geo/clay/NE.webp'
import m127 from '../../assets/geo/clay/NG.webp'
import m128 from '../../assets/geo/clay/NI.webp'
import m129 from '../../assets/geo/clay/NL.webp'
import m130 from '../../assets/geo/clay/NO.webp'
import m131 from '../../assets/geo/clay/NP.webp'
import m132 from '../../assets/geo/clay/NR.webp'
import m133 from '../../assets/geo/clay/NZ.webp'
import m134 from '../../assets/geo/clay/OM.webp'
import m135 from '../../assets/geo/clay/PA.webp'
import m136 from '../../assets/geo/clay/PE.webp'
import m137 from '../../assets/geo/clay/PG.webp'
import m138 from '../../assets/geo/clay/PH.webp'
import m139 from '../../assets/geo/clay/PK.webp'
import m140 from '../../assets/geo/clay/PL.webp'
import m141 from '../../assets/geo/clay/PT.webp'
import m142 from '../../assets/geo/clay/PW.webp'
import m143 from '../../assets/geo/clay/PY.webp'
import m144 from '../../assets/geo/clay/QA.webp'
import m145 from '../../assets/geo/clay/RO.webp'
import m146 from '../../assets/geo/clay/RS.webp'
import m147 from '../../assets/geo/clay/RU.webp'
import m148 from '../../assets/geo/clay/RW.webp'
import m149 from '../../assets/geo/clay/SA.webp'
import m150 from '../../assets/geo/clay/SB.webp'
import m151 from '../../assets/geo/clay/SC.webp'
import m152 from '../../assets/geo/clay/SD.webp'
import m153 from '../../assets/geo/clay/SE.webp'
import m154 from '../../assets/geo/clay/SG.webp'
import m155 from '../../assets/geo/clay/SI.webp'
import m156 from '../../assets/geo/clay/SK.webp'
import m157 from '../../assets/geo/clay/SL.webp'
import m158 from '../../assets/geo/clay/SM.webp'
import m159 from '../../assets/geo/clay/SN.webp'
import m160 from '../../assets/geo/clay/SO.webp'
import m161 from '../../assets/geo/clay/SR.webp'
import m162 from '../../assets/geo/clay/SS.webp'
import m163 from '../../assets/geo/clay/ST.webp'
import m164 from '../../assets/geo/clay/SV.webp'
import m165 from '../../assets/geo/clay/SY.webp'
import m166 from '../../assets/geo/clay/SZ.webp'
import m167 from '../../assets/geo/clay/TD.webp'
import m168 from '../../assets/geo/clay/TG.webp'
import m169 from '../../assets/geo/clay/TH.webp'
import m170 from '../../assets/geo/clay/TJ.webp'
import m171 from '../../assets/geo/clay/TL.webp'
import m172 from '../../assets/geo/clay/TM.webp'
import m173 from '../../assets/geo/clay/TN.webp'
import m174 from '../../assets/geo/clay/TO.webp'
import m175 from '../../assets/geo/clay/TR.webp'
import m176 from '../../assets/geo/clay/TT.webp'
import m177 from '../../assets/geo/clay/TV.webp'
import m178 from '../../assets/geo/clay/TZ.webp'
import m179 from '../../assets/geo/clay/UA.webp'
import m180 from '../../assets/geo/clay/UG.webp'
import m181 from '../../assets/geo/clay/US.webp'
import m182 from '../../assets/geo/clay/UY.webp'
import m183 from '../../assets/geo/clay/UZ.webp'
import m184 from '../../assets/geo/clay/VA.webp'
import m185 from '../../assets/geo/clay/VC.webp'
import m186 from '../../assets/geo/clay/VE.webp'
import m187 from '../../assets/geo/clay/VN.webp'
import m188 from '../../assets/geo/clay/VU.webp'
import m189 from '../../assets/geo/clay/WS.webp'
import m190 from '../../assets/geo/clay/YE.webp'
import m191 from '../../assets/geo/clay/ZA.webp'
import m192 from '../../assets/geo/clay/ZM.webp'
import m193 from '../../assets/geo/clay/ZW.webp'
import m194 from '../../assets/geo/clay/region-AF.webp'
import m195 from '../../assets/geo/clay/region-AS.webp'
import m196 from '../../assets/geo/clay/region-EU.webp'
import m197 from '../../assets/geo/clay/region-NA.webp'
import m198 from '../../assets/geo/clay/region-OC.webp'
import m199 from '../../assets/geo/clay/region-SA.webp'
import m200 from '../../assets/geo/clay/region-AN.webp'
import m201 from '../../assets/geo/clay/world.webp'
export const CLAY_MAPS: Readonly<Record<string, number | string>> = {
  'AD': m0,
  'AE': m1,
  'AF': m2,
  'AG': m3,
  'AL': m4,
  'AM': m5,
  'AO': m6,
  'AR': m7,
  'AT': m8,
  'AU': m9,
  'AZ': m10,
  'BA': m11,
  'BB': m12,
  'BD': m13,
  'BE': m14,
  'BF': m15,
  'BG': m16,
  'BH': m17,
  'BI': m18,
  'BJ': m19,
  'BN': m20,
  'BO': m21,
  'BR': m22,
  'BS': m23,
  'BT': m24,
  'BW': m25,
  'BY': m26,
  'BZ': m27,
  'CA': m28,
  'CD': m29,
  'CF': m30,
  'CG': m31,
  'CH': m32,
  'CI': m33,
  'CL': m34,
  'CM': m35,
  'CN': m36,
  'CO': m37,
  'CR': m38,
  'CU': m39,
  'CV': m40,
  'CY': m41,
  'CZ': m42,
  'DE': m43,
  'DJ': m44,
  'DK': m45,
  'DM': m46,
  'DO': m47,
  'DZ': m48,
  'EC': m49,
  'EE': m50,
  'EG': m51,
  'ER': m52,
  'ES': m53,
  'ET': m54,
  'FI': m55,
  'FJ': m56,
  'FM': m57,
  'FR': m58,
  'GA': m59,
  'GB': m60,
  'GD': m61,
  'GE': m62,
  'GH': m63,
  'GM': m64,
  'GN': m65,
  'GQ': m66,
  'GR': m67,
  'GT': m68,
  'GW': m69,
  'GY': m70,
  'HN': m71,
  'HR': m72,
  'HT': m73,
  'HU': m74,
  'ID': m75,
  'IE': m76,
  'IL': m77,
  'IN': m78,
  'IQ': m79,
  'IR': m80,
  'IS': m81,
  'IT': m82,
  'JM': m83,
  'JO': m84,
  'JP': m85,
  'KE': m86,
  'KG': m87,
  'KH': m88,
  'KI': m89,
  'KM': m90,
  'KN': m91,
  'KP': m92,
  'KR': m93,
  'KW': m94,
  'KZ': m95,
  'LA': m96,
  'LB': m97,
  'LC': m98,
  'LI': m99,
  'LK': m100,
  'LR': m101,
  'LS': m102,
  'LT': m103,
  'LU': m104,
  'LV': m105,
  'LY': m106,
  'MA': m107,
  'MC': m108,
  'MD': m109,
  'ME': m110,
  'MG': m111,
  'MH': m112,
  'MK': m113,
  'ML': m114,
  'MM': m115,
  'MN': m116,
  'MR': m117,
  'MT': m118,
  'MU': m119,
  'MV': m120,
  'MW': m121,
  'MX': m122,
  'MY': m123,
  'MZ': m124,
  'NA': m125,
  'NE': m126,
  'NG': m127,
  'NI': m128,
  'NL': m129,
  'NO': m130,
  'NP': m131,
  'NR': m132,
  'NZ': m133,
  'OM': m134,
  'PA': m135,
  'PE': m136,
  'PG': m137,
  'PH': m138,
  'PK': m139,
  'PL': m140,
  'PT': m141,
  'PW': m142,
  'PY': m143,
  'QA': m144,
  'RO': m145,
  'RS': m146,
  'RU': m147,
  'RW': m148,
  'SA': m149,
  'SB': m150,
  'SC': m151,
  'SD': m152,
  'SE': m153,
  'SG': m154,
  'SI': m155,
  'SK': m156,
  'SL': m157,
  'SM': m158,
  'SN': m159,
  'SO': m160,
  'SR': m161,
  'SS': m162,
  'ST': m163,
  'SV': m164,
  'SY': m165,
  'SZ': m166,
  'TD': m167,
  'TG': m168,
  'TH': m169,
  'TJ': m170,
  'TL': m171,
  'TM': m172,
  'TN': m173,
  'TO': m174,
  'TR': m175,
  'TT': m176,
  'TV': m177,
  'TZ': m178,
  'UA': m179,
  'UG': m180,
  'US': m181,
  'UY': m182,
  'UZ': m183,
  'VA': m184,
  'VC': m185,
  'VE': m186,
  'VN': m187,
  'VU': m188,
  'WS': m189,
  'YE': m190,
  'ZA': m191,
  'ZM': m192,
  'ZW': m193,
  'region-AF': m194,
  'region-AS': m195,
  'region-EU': m196,
  'region-NA': m197,
  'region-OC': m198,
  'region-SA': m199,
  'region-AN': m200,
  'world': m201,
}
