// Generated by node scripts/build-explorer-chest-art.cjs. Preserve masters, alpha and frame alignment.
import closed from '../../assets/art/explorer-chest/closed.webp'
import opened from '../../assets/art/explorer-chest/opened.webp'
import sheet from '../../assets/art/explorer-chest/chest-sheet.webp'

export const EXPLORER_CHEST = { closed, opened, sheet } as const
export const EXPLORER_CHEST_SEQUENCE = { frames: 40, columns: 8, rows: 5, fps: 20, frameSize: 480 } as const
export const EXPLORER_CHEST_GEOMETRY = {
  "closed": {
    "x": 0.109375,
    "y": 0.2984375,
    "w": 0.7953125,
    "h": 0.6578125,
    "aspect": 1
  },
  "opened": {
    "x": 0.04375,
    "y": 0.0328125,
    "w": 0.8578125,
    "h": 0.9234375,
    "aspect": 1
  }
} as const
