/**
 * GENERATED by `pnpm build:flags` — do not edit.
 *
 * Flag artwork rasterised from flag-icons (MIT). See scripts/build-flags.cjs for why
 * these are PNG rather than SVG, and why they are 600×450.
 */

import US from '../../assets/flags/US.png'
import CA from '../../assets/flags/CA.png'
import MX from '../../assets/flags/MX.png'
import CU from '../../assets/flags/CU.png'
import GT from '../../assets/flags/GT.png'
import CR from '../../assets/flags/CR.png'
import PA from '../../assets/flags/PA.png'
import ID from '../../assets/flags/ID.png'
import TH from '../../assets/flags/TH.png'
import VN from '../../assets/flags/VN.png'
import PH from '../../assets/flags/PH.png'
import MY from '../../assets/flags/MY.png'
import AU from '../../assets/flags/AU.png'
import NZ from '../../assets/flags/NZ.png'
import FJ from '../../assets/flags/FJ.png'
import PG from '../../assets/flags/PG.png'
import PL from '../../assets/flags/PL.png'
import UA from '../../assets/flags/UA.png'
import CZ from '../../assets/flags/CZ.png'
import HU from '../../assets/flags/HU.png'
import RO from '../../assets/flags/RO.png'
import IN from '../../assets/flags/IN.png'
import PK from '../../assets/flags/PK.png'
import BD from '../../assets/flags/BD.png'
import NP from '../../assets/flags/NP.png'
import EG from '../../assets/flags/EG.png'
import MA from '../../assets/flags/MA.png'
import DZ from '../../assets/flags/DZ.png'
import TN from '../../assets/flags/TN.png'
import NG from '../../assets/flags/NG.png'
import GH from '../../assets/flags/GH.png'
import SN from '../../assets/flags/SN.png'
import ML from '../../assets/flags/ML.png'
import KE from '../../assets/flags/KE.png'
import ET from '../../assets/flags/ET.png'
import ZA from '../../assets/flags/ZA.png'
import UG from '../../assets/flags/UG.png'
import TZ from '../../assets/flags/TZ.png'
import NA from '../../assets/flags/NA.png'
import BW from '../../assets/flags/BW.png'
import ZW from '../../assets/flags/ZW.png'
import JP from '../../assets/flags/JP.png'
import CN from '../../assets/flags/CN.png'
import KR from '../../assets/flags/KR.png'
import KP from '../../assets/flags/KP.png'
import MN from '../../assets/flags/MN.png'
import BR from '../../assets/flags/BR.png'
import AR from '../../assets/flags/AR.png'
import CL from '../../assets/flags/CL.png'
import PE from '../../assets/flags/PE.png'
import CO from '../../assets/flags/CO.png'
import IT from '../../assets/flags/IT.png'
import ES from '../../assets/flags/ES.png'
import PT from '../../assets/flags/PT.png'
import GR from '../../assets/flags/GR.png'
import FR from '../../assets/flags/FR.png'
import DE from '../../assets/flags/DE.png'
import BE from '../../assets/flags/BE.png'
import NL from '../../assets/flags/NL.png'
import AT from '../../assets/flags/AT.png'
import CH from '../../assets/flags/CH.png'
import SE from '../../assets/flags/SE.png'
import NO from '../../assets/flags/NO.png'
import DK from '../../assets/flags/DK.png'
import FI from '../../assets/flags/FI.png'

/**
 * Metro hands back an opaque numeric handle; Vite — vitest and the screenshot
 * harness — hands back a URL string. Both are real, so the type admits both and
 * `flagSource` in ./flags.ts narrows them to something `Image` accepts.
 */
export type AssetModule = number | string

/** Content-pack asset path → the bundled image. */
export const FLAG_BY_PATH: Readonly<Record<string, AssetModule>> = {
  'flags/US.png': US,
  'flags/CA.png': CA,
  'flags/MX.png': MX,
  'flags/CU.png': CU,
  'flags/GT.png': GT,
  'flags/CR.png': CR,
  'flags/PA.png': PA,
  'flags/ID.png': ID,
  'flags/TH.png': TH,
  'flags/VN.png': VN,
  'flags/PH.png': PH,
  'flags/MY.png': MY,
  'flags/AU.png': AU,
  'flags/NZ.png': NZ,
  'flags/FJ.png': FJ,
  'flags/PG.png': PG,
  'flags/PL.png': PL,
  'flags/UA.png': UA,
  'flags/CZ.png': CZ,
  'flags/HU.png': HU,
  'flags/RO.png': RO,
  'flags/IN.png': IN,
  'flags/PK.png': PK,
  'flags/BD.png': BD,
  'flags/NP.png': NP,
  'flags/EG.png': EG,
  'flags/MA.png': MA,
  'flags/DZ.png': DZ,
  'flags/TN.png': TN,
  'flags/NG.png': NG,
  'flags/GH.png': GH,
  'flags/SN.png': SN,
  'flags/ML.png': ML,
  'flags/KE.png': KE,
  'flags/ET.png': ET,
  'flags/ZA.png': ZA,
  'flags/UG.png': UG,
  'flags/TZ.png': TZ,
  'flags/NA.png': NA,
  'flags/BW.png': BW,
  'flags/ZW.png': ZW,
  'flags/JP.png': JP,
  'flags/CN.png': CN,
  'flags/KR.png': KR,
  'flags/KP.png': KP,
  'flags/MN.png': MN,
  'flags/BR.png': BR,
  'flags/AR.png': AR,
  'flags/CL.png': CL,
  'flags/PE.png': PE,
  'flags/CO.png': CO,
  'flags/IT.png': IT,
  'flags/ES.png': ES,
  'flags/PT.png': PT,
  'flags/GR.png': GR,
  'flags/FR.png': FR,
  'flags/DE.png': DE,
  'flags/BE.png': BE,
  'flags/NL.png': NL,
  'flags/AT.png': AT,
  'flags/CH.png': CH,
  'flags/SE.png': SE,
  'flags/NO.png': NO,
  'flags/DK.png': DK,
  'flags/FI.png': FI,
}
