/**
 * GENERATED by `pnpm build:icons` — do not edit.
 *
 * Icon artwork rasterised from Lucide 1.28.0 (ISC). See
 * scripts/build-icons.cjs for why these are PNG alpha masks rather than SVG.
 *
 * Every file is white-on-transparent, so it is a MASK: the colour comes from
 * `tintColor` at the call site and one file serves every state the theme has.
 */

import home from '../../assets/icons/home.png'
import explore from '../../assets/icons/explore.png'
import quests from '../../assets/icons/quests.png'
import profile from '../../assets/icons/profile.png'
import more from '../../assets/icons/more.png'
import back from '../../assets/icons/back.png'
import forward from '../../assets/icons/forward.png'
import chevron from '../../assets/icons/chevron.png'
import close from '../../assets/icons/close.png'
import check from '../../assets/icons/check.png'
import streak from '../../assets/icons/streak.png'
import xp from '../../assets/icons/xp.png'
import coins from '../../assets/icons/coins.png'
import gem from '../../assets/icons/gem.png'
import heart from '../../assets/icons/heart.png'
import trophy from '../../assets/icons/trophy.png'
import globe from '../../assets/icons/globe.png'
import map from '../../assets/icons/map.png'
import pin from '../../assets/icons/pin.png'
import flag from '../../assets/icons/flag.png'
import star from '../../assets/icons/star.png'
import lock from '../../assets/icons/lock.png'
import medal from '../../assets/icons/medal.png'
import bell from '../../assets/icons/bell.png'
import offline from '../../assets/icons/offline.png'
import failure from '../../assets/icons/failure.png'
import shop from '../../assets/icons/shop.png'
import capital from '../../assets/icons/capital.png'
import currency from '../../assets/icons/currency.png'
import language from '../../assets/icons/language.png'
import callingCode from '../../assets/icons/callingCode.png'
import continent from '../../assets/icons/continent.png'
import settings from '../../assets/icons/settings.png'
import edit from '../../assets/icons/edit.png'
import clock from '../../assets/icons/clock.png'
import moon from '../../assets/icons/moon.png'
import sunrise from '../../assets/icons/sunrise.png'

/** Metro hands back a numeric handle; Vite hands back a URL string. Both are real. */
export type IconAsset = number | string

export type IconName =
  | 'home'
  | 'explore'
  | 'quests'
  | 'profile'
  | 'more'
  | 'back'
  | 'forward'
  | 'chevron'
  | 'close'
  | 'check'
  | 'streak'
  | 'xp'
  | 'coins'
  | 'gem'
  | 'heart'
  | 'trophy'
  | 'globe'
  | 'map'
  | 'pin'
  | 'flag'
  | 'star'
  | 'lock'
  | 'medal'
  | 'bell'
  | 'offline'
  | 'failure'
  | 'shop'
  | 'capital'
  | 'currency'
  | 'language'
  | 'callingCode'
  | 'continent'
  | 'settings'
  | 'edit'
  | 'clock'
  | 'moon'
  | 'sunrise'

export const ICON_BY_NAME: Readonly<Record<IconName, IconAsset>> = {
  'home': home,
  'explore': explore,
  'quests': quests,
  'profile': profile,
  'more': more,
  'back': back,
  'forward': forward,
  'chevron': chevron,
  'close': close,
  'check': check,
  'streak': streak,
  'xp': xp,
  'coins': coins,
  'gem': gem,
  'heart': heart,
  'trophy': trophy,
  'globe': globe,
  'map': map,
  'pin': pin,
  'flag': flag,
  'star': star,
  'lock': lock,
  'medal': medal,
  'bell': bell,
  'offline': offline,
  'failure': failure,
  'shop': shop,
  'capital': capital,
  'currency': currency,
  'language': language,
  'callingCode': callingCode,
  'continent': continent,
  'settings': settings,
  'edit': edit,
  'clock': clock,
  'moon': moon,
  'sunrise': sunrise,
}
