/**
 * GENERATED by `pnpm build:maps` — do not edit.
 *
 * Outlines projected from Natural Earth (public domain) via world-atlas. See
 * scripts/build-maps.cjs for the projection, the two-layer scheme, and why these are
 * PNG rather than SVG.
 *
 * Both layers are single-colour alpha masks: tint them with a design token rather than
 * treating them as artwork with a colour of their own.
 */

import region_AF from '../../assets/geo/regions/AF.png'
import region_AS from '../../assets/geo/regions/AS.png'
import region_EU from '../../assets/geo/regions/EU.png'
import region_NA from '../../assets/geo/regions/NA.png'
import region_OC from '../../assets/geo/regions/OC.png'
import region_SA from '../../assets/geo/regions/SA.png'
import country_AR from '../../assets/geo/countries/AR.png'
import country_AT from '../../assets/geo/countries/AT.png'
import country_AU from '../../assets/geo/countries/AU.png'
import country_BD from '../../assets/geo/countries/BD.png'
import country_BE from '../../assets/geo/countries/BE.png'
import country_BR from '../../assets/geo/countries/BR.png'
import country_BW from '../../assets/geo/countries/BW.png'
import country_CA from '../../assets/geo/countries/CA.png'
import country_CH from '../../assets/geo/countries/CH.png'
import country_CL from '../../assets/geo/countries/CL.png'
import country_CN from '../../assets/geo/countries/CN.png'
import country_CO from '../../assets/geo/countries/CO.png'
import country_CR from '../../assets/geo/countries/CR.png'
import country_CU from '../../assets/geo/countries/CU.png'
import country_CZ from '../../assets/geo/countries/CZ.png'
import country_DE from '../../assets/geo/countries/DE.png'
import country_DK from '../../assets/geo/countries/DK.png'
import country_DZ from '../../assets/geo/countries/DZ.png'
import country_EG from '../../assets/geo/countries/EG.png'
import country_ES from '../../assets/geo/countries/ES.png'
import country_ET from '../../assets/geo/countries/ET.png'
import country_FI from '../../assets/geo/countries/FI.png'
import country_FJ from '../../assets/geo/countries/FJ.png'
import country_FR from '../../assets/geo/countries/FR.png'
import country_GH from '../../assets/geo/countries/GH.png'
import country_GR from '../../assets/geo/countries/GR.png'
import country_GT from '../../assets/geo/countries/GT.png'
import country_HU from '../../assets/geo/countries/HU.png'
import country_ID from '../../assets/geo/countries/ID.png'
import country_IN from '../../assets/geo/countries/IN.png'
import country_IT from '../../assets/geo/countries/IT.png'
import country_JP from '../../assets/geo/countries/JP.png'
import country_KE from '../../assets/geo/countries/KE.png'
import country_KP from '../../assets/geo/countries/KP.png'
import country_KR from '../../assets/geo/countries/KR.png'
import country_MA from '../../assets/geo/countries/MA.png'
import country_ML from '../../assets/geo/countries/ML.png'
import country_MN from '../../assets/geo/countries/MN.png'
import country_MX from '../../assets/geo/countries/MX.png'
import country_MY from '../../assets/geo/countries/MY.png'
import country_NA from '../../assets/geo/countries/NA.png'
import country_NG from '../../assets/geo/countries/NG.png'
import country_NL from '../../assets/geo/countries/NL.png'
import country_NO from '../../assets/geo/countries/NO.png'
import country_NP from '../../assets/geo/countries/NP.png'
import country_NZ from '../../assets/geo/countries/NZ.png'
import country_PA from '../../assets/geo/countries/PA.png'
import country_PE from '../../assets/geo/countries/PE.png'
import country_PG from '../../assets/geo/countries/PG.png'
import country_PH from '../../assets/geo/countries/PH.png'
import country_PK from '../../assets/geo/countries/PK.png'
import country_PL from '../../assets/geo/countries/PL.png'
import country_PT from '../../assets/geo/countries/PT.png'
import country_RO from '../../assets/geo/countries/RO.png'
import country_SE from '../../assets/geo/countries/SE.png'
import country_SN from '../../assets/geo/countries/SN.png'
import country_TH from '../../assets/geo/countries/TH.png'
import country_TN from '../../assets/geo/countries/TN.png'
import country_TZ from '../../assets/geo/countries/TZ.png'
import country_UA from '../../assets/geo/countries/UA.png'
import country_UG from '../../assets/geo/countries/UG.png'
import country_US from '../../assets/geo/countries/US.png'
import country_VN from '../../assets/geo/countries/VN.png'
import country_ZA from '../../assets/geo/countries/ZA.png'
import country_ZW from '../../assets/geo/countries/ZW.png'

import type { AssetModule } from './flags.generated.js'

/** Content-pack asset path → the bundled image. */
export const MAP_BY_PATH: Readonly<Record<string, AssetModule>> = {
  'geo/regions/AF.png': region_AF,
  'geo/regions/AS.png': region_AS,
  'geo/regions/EU.png': region_EU,
  'geo/regions/NA.png': region_NA,
  'geo/regions/OC.png': region_OC,
  'geo/regions/SA.png': region_SA,
  'geo/countries/AR.png': country_AR,
  'geo/countries/AT.png': country_AT,
  'geo/countries/AU.png': country_AU,
  'geo/countries/BD.png': country_BD,
  'geo/countries/BE.png': country_BE,
  'geo/countries/BR.png': country_BR,
  'geo/countries/BW.png': country_BW,
  'geo/countries/CA.png': country_CA,
  'geo/countries/CH.png': country_CH,
  'geo/countries/CL.png': country_CL,
  'geo/countries/CN.png': country_CN,
  'geo/countries/CO.png': country_CO,
  'geo/countries/CR.png': country_CR,
  'geo/countries/CU.png': country_CU,
  'geo/countries/CZ.png': country_CZ,
  'geo/countries/DE.png': country_DE,
  'geo/countries/DK.png': country_DK,
  'geo/countries/DZ.png': country_DZ,
  'geo/countries/EG.png': country_EG,
  'geo/countries/ES.png': country_ES,
  'geo/countries/ET.png': country_ET,
  'geo/countries/FI.png': country_FI,
  'geo/countries/FJ.png': country_FJ,
  'geo/countries/FR.png': country_FR,
  'geo/countries/GH.png': country_GH,
  'geo/countries/GR.png': country_GR,
  'geo/countries/GT.png': country_GT,
  'geo/countries/HU.png': country_HU,
  'geo/countries/ID.png': country_ID,
  'geo/countries/IN.png': country_IN,
  'geo/countries/IT.png': country_IT,
  'geo/countries/JP.png': country_JP,
  'geo/countries/KE.png': country_KE,
  'geo/countries/KP.png': country_KP,
  'geo/countries/KR.png': country_KR,
  'geo/countries/MA.png': country_MA,
  'geo/countries/ML.png': country_ML,
  'geo/countries/MN.png': country_MN,
  'geo/countries/MX.png': country_MX,
  'geo/countries/MY.png': country_MY,
  'geo/countries/NA.png': country_NA,
  'geo/countries/NG.png': country_NG,
  'geo/countries/NL.png': country_NL,
  'geo/countries/NO.png': country_NO,
  'geo/countries/NP.png': country_NP,
  'geo/countries/NZ.png': country_NZ,
  'geo/countries/PA.png': country_PA,
  'geo/countries/PE.png': country_PE,
  'geo/countries/PG.png': country_PG,
  'geo/countries/PH.png': country_PH,
  'geo/countries/PK.png': country_PK,
  'geo/countries/PL.png': country_PL,
  'geo/countries/PT.png': country_PT,
  'geo/countries/RO.png': country_RO,
  'geo/countries/SE.png': country_SE,
  'geo/countries/SN.png': country_SN,
  'geo/countries/TH.png': country_TH,
  'geo/countries/TN.png': country_TN,
  'geo/countries/TZ.png': country_TZ,
  'geo/countries/UA.png': country_UA,
  'geo/countries/UG.png': country_UG,
  'geo/countries/US.png': country_US,
  'geo/countries/VN.png': country_VN,
  'geo/countries/ZA.png': country_ZA,
  'geo/countries/ZW.png': country_ZW,
}
