// Generated by build-soft-assets.cjs from inspected 3D renders.
import chest from '../../assets/art/soft/chest-closed.webp'
import gem from '../../assets/art/soft/chest-gem.webp'
export const CHEST_SEQUENCE = { frames: 40, fps: 20, columns: 8, rows: 5 } as const
export const SOFT_ART = {
  'treasure-chest': { asset: chest, geometry: {"aspect":1,"x":0.121875,"y":0.35625,"w":0.615625,"h":0.4875} },
  gem: { asset: gem, geometry: {"aspect":1,"x":0.19140625,"y":0.15234375,"w":0.6171875,"h":0.71484375} },
} as const
