/**
 * Localisation — init, detection, fallback, and the one typed `t`.
 *
 * This replaces the hand-written shim that carried Phase 1. The shim did the two
 * things that were expensive to retrofit (every string a key, ICU-shaped plurals) and
 * nothing else; it could not do Swedish plural rules, gendered forms, or a language
 * change without a restart. i18next can, and ICU is the reason the locale files did
 * not have to change to get here.
 *
 * The call shape is deliberately narrower than i18next's: one `t`, typed against the
 * generated key union, with the placeholders each key needs enforced at compile time.
 * A missing placeholder renders as literal `{time}` on screen — invisible to a test
 * that only asserts the key resolved, obvious to a user, and we shipped it once.
 *
 * Spec: docs/engineering/localization.md · docs/adr/0009-localization.md
 */

// FIRST, and for its side effect. Hermes ships no `Intl.PluralRules`, so without this
// every plural in the app formats to its own ICU source on a real device while
// formatting perfectly in Node, jsdom and Chromium — which is every environment that
// tests it. See intl-polyfill.ts for the whole story; it must be evaluated before the
// `i18next.init` below builds its first formatter.
import { hasPluralRules } from './intl-polyfill.js'
import i18next, { type i18n as I18nInstance } from 'i18next'
import { IcuFormat } from './icu.js'
import { pseudo } from './pseudo.js'
import { NAMESPACES, type Namespace, type TranslationKey, type TranslationParams } from './keys.js'

import { CATALOGUE } from './catalogue.generated.js'

export * from './format.js'
export { NAMESPACES, type Namespace, type TranslationKey, type TranslationParams }

/**
 * Development-only warnings, without assuming which runtime we are in.
 *
 * This package runs in three: Metro (which defines `__DEV__` and inlines
 * `process.env.NODE_ENV`), Node (tests and scripts), and eventually a web bundler.
 * Reading `process` directly would force `@types/node` into the React Native app's
 * tsconfig, which puts `fs` and `child_process` in autocomplete for screen code —
 * a bad trade for one boolean.
 */
const isDev = (): boolean => {
  const runtime = globalThis as {
    __DEV__?: boolean
    process?: { env?: Record<string, string | undefined> }
  }
  if (typeof runtime.__DEV__ === 'boolean') return runtime.__DEV__
  return runtime.process?.env?.['NODE_ENV'] !== 'production'
}

/** Shipped in v1.0. Spanish, German, French and Portuguese follow in v2.0. */
export const SUPPORTED_LOCALES = ['en', 'sv'] as const
export type Locale = (typeof SUPPORTED_LOCALES)[number]
export const FALLBACK_LOCALE: Locale = 'en'

/** Not in `SUPPORTED_LOCALES` — a development tool, never a shipped language. */
export const PSEUDO_LOCALE = 'en-XA'

/**
 * Each language's name IN ITSELF, which is the only correct way to label a picker.
 *
 * A Swedish speaker looking for their language scans for *Svenska*, not for *Swedish*.
 * Labelling the list in the CURRENT language is the classic mistake: it works for
 * everybody who can already read the app and fails for exactly the person the picker
 * exists to help — somebody who opened it because they cannot.
 *
 * So these are NOT translation keys and never will be. A key would have one value per
 * locale, which is the bug; an endonym has one value, full stop.
 *
 * Typed as `Record<Locale, string>`, so adding a locale to `SUPPORTED_LOCALES` without
 * naming it here is a compile error rather than a picker row reading `de`.
 */
export const LOCALE_ENDONYM: Record<Locale, string> = {
  en: 'English',
  sv: 'Svenska',
}

// ── resources ───────────────────────────────────────────────────────────────

/**
 * Core locales ship IN THE BINARY. A first launch on a plane must render words, and a
 * translation bundle is a few kilobytes — the download is not worth the failure mode.
 *
 * ## Why this is one generated import and not forty-four JSON ones
 *
 * It used to be forty-four `import … from '../locales/…json'` lines, a `RAW` map naming
 * each one twice, and a `toBundle` that walked all 629 keys on the first frame to drop the
 * `__note` entries and strip the namespace prefixes.
 *
 * All three jobs now happen at build time, in `scripts/build-catalogue.ts`. The reason is
 * the notes: they are half the catalogue by bytes, they are written for a translator, and
 * skipping them at runtime still meant Hermes had parsed every one of them to get to the
 * strings. Removing them from the bundle moved iOS from 4.60 MB to 4.52 — measured on the
 * compiled bytecode, which is the only measurement `scripts/bundle-native.cjs` accepts.
 *
 * The notes have not gone anywhere. They are still in `locales/`, still required by
 * `pnpm i18n:check`, still the thing a translator opens. They just stop being shipped to a
 * device that has no translator on it.
 *
 * `CATALOGUE` is regenerated by `pnpm i18n:types`, which `pnpm generate` runs, which
 * `pnpm verify` runs first — so it cannot drift from `locales/` and survive a verify.
 */
const resources = CATALOGUE

// ── the instance ────────────────────────────────────────────────────────────

/**
 * Our own instance rather than the global one. Two libraries initialising the same
 * global i18next is a class of bug that only appears once a dependency also uses it,
 * and by then it is someone else's stack trace.
 */
export const i18n: I18nInstance = i18next.createInstance()

i18n
  .use(
    new IcuFormat({
      /**
       * A malformed ICU string must never fail silently. The default behaviour of
       * every library in this space is to render the raw pattern, which reaches the
       * user as `{count, plural, one {# day streak} ...}` and reaches the developer
       * as nothing at all.
       */
      onError: (error, key, value) => {
        if (isDev()) {
          console.error(`[i18n] ICU parse failed for "${key}": ${error.message}\n  ${value}`)
          // The one cause worth naming rather than leaving to be re-diagnosed. Every
          // plural in the app failed this way on device for as long as the engine had
          // no `Intl.PluralRules`, and the message above — "Intl.PluralRules is not
          // available in this environment" — is the only trace it left, in a console
          // nobody reads on a phone.
          if (!hasPluralRules()) {
            console.error(
              '[i18n] Intl.PluralRules is missing and the polyfill did not take. ' +
                'Every plural string will render as raw ICU. See src/intl-polyfill.ts.',
            )
          }
        }
        return value
      },
    }),
  )
  .init({
    lng: FALLBACK_LOCALE,
    fallbackLng: FALLBACK_LOCALE,
    // The pseudo-locale is listed so i18next does not reject it when a dev build
    // switches to it. It has no bundle until `enablePseudoLocale` builds one, and
    // `resolveLocale` never returns it, so no user can land here by accident.
    supportedLngs: [...SUPPORTED_LOCALES, PSEUDO_LOCALE],
    ns: NAMESPACES,
    defaultNS: 'common',
    resources,
    // Keys contain dots (`greeting.morning`) and the bundles are flat, so dot must NOT
    // be read as a path into a nested object. The namespace separator stays `:`.
    keySeparator: false,
    nsSeparator: ':',
    // Synchronous init. Screens call `t` during their first render; an async init means
    // the first frame renders raw keys and then flickers into real copy.
    initImmediate: false,
    interpolation: {
      // React already escapes. Double-escaping turns "Côte d'Ivoire" into mojibake.
      escapeValue: false,
    },
    returnNull: false,
  })

// ── the typed t ─────────────────────────────────────────────────────────────

/**
 * Params are required exactly when the English string has placeholders, and omitted
 * entirely when it does not — so `t('common:continue')` stays a one-argument call
 * while `t('home:level')` cannot compile without `{ level }`.
 */
export type TranslationArgs<K extends TranslationKey> =
  keyof TranslationParams[K] extends never ? [] : [params: TranslationParams[K]]

export function t<K extends TranslationKey>(key: K, ...args: TranslationArgs<K>): string {
  if (isDev() && !i18n.exists(key)) {
    // Only reachable if keys.ts is stale — regenerate with `pnpm i18n:types`.
    console.warn(`[i18n] missing key: ${key}`)
    return key
  }
  // Branch rather than pass `undefined`: i18next's second parameter is overloaded on
  // `string` (a default value) as well as an options object, so an explicit
  // `undefined` picks the wrong overload.
  const params = args[0] as Record<string, unknown> | undefined
  return params === undefined ? i18n.t(key) : i18n.t(key, params)
}

/**
 * `t` for keys that come from a content pack rather than from source.
 *
 * A question template names its own prompt (`lesson:prompt.capital_of`) and supplies
 * its own parameters, so neither can be checked against the generated union — the
 * compiler cannot see a JSON file that ships separately from the binary.
 *
 * That check does not disappear, it moves: `pnpm content:validate` fails a pack whose
 * template references a key the catalogue does not have. Use this ONLY where the key
 * genuinely originates in content. Everywhere else, `t` is the one to reach for, and
 * reaching for this instead silently opts out of the type safety.
 */
export function tContent(key: string, params?: Record<string, string | number>): string {
  if (!i18n.exists(key)) {
    if (isDev()) console.warn(`[i18n] content referenced a missing key: ${key}`)
    return key
  }
  return params === undefined ? i18n.t(key) : i18n.t(key, params)
}

// ── locale selection ────────────────────────────────────────────────────────

const isSupported = (value: string): value is Locale =>
  (SUPPORTED_LOCALES as readonly string[]).includes(value)

/**
 * First supported locale among the candidates, falling back to English.
 *
 * Candidates are tried in order and each is also tried without its region, so a
 * `sv-FI` device gets Swedish rather than English (spec §7). The app passes, in
 * order: the user's saved choice, then the device's preferred languages.
 */
export function resolveLocale(candidates: readonly string[]): Locale {
  for (const candidate of candidates) {
    if (!candidate) continue
    if (isSupported(candidate)) return candidate
    const language = candidate.split(/[-_]/)[0]
    if (language && isSupported(language)) return language
  }
  return FALLBACK_LOCALE
}

/**
 * Applies immediately, without a restart (spec §7). Components re-render because they
 * subscribe through react-i18next; anything reading `t` outside React picks up the
 * new language on its next call.
 */
export async function setLocale(locale: Locale): Promise<void> {
  if (i18n.language === locale) return
  await i18n.changeLanguage(locale)
}

// ── pseudo-locale ───────────────────────────────────────────────────────────

/**
 * Adds `en-XA` and switches to it.
 *
 * German and Finnish run about 40% longer than English. Testing a layout only in
 * English means finding that out in a screenshot from a translator, months later,
 * after the layout has been copied into six other screens.
 *
 * The bundle is built in memory from the English one, so it can never be stale and
 * there is nothing to generate or commit. The accents also make untranslated strings
 * obvious: anything still rendering in plain ASCII never went through `t()`.
 *
 * A no-op in production. Not because shipping it would be catastrophic, but because
 * a language nobody speaks appearing in a picker is a support ticket.
 *
 * ## Except when something asks for it on purpose
 *
 * `globalThis.__WQ_PSEUDO__` overrides the production gate, and it exists because the
 * gate had made this function unreachable in the one place it was most useful. The
 * Definition of Done asks for "pseudo-locale screenshots clean"; the screenshot harness
 * drives the EXPORTED bundle, which is production, so `isDev()` was false and this
 * returned false — and nothing said so. `pnpm i18n:pseudo` wrote files nobody rendered
 * and this function had no caller outside its own unit test for as long as it existed.
 *
 * A global rather than a parameter, because the caller that needs it is a Playwright
 * script reaching into a page it did not compile. It cannot change a call site, only the
 * window it evaluates in.
 *
 * This is not a way into production: nothing sets it, `SUPPORTED_LOCALES` still excludes
 * `en-XA`, and the language picker reads `LANGUAGE_CHOICES` rather than the loaded
 * bundles — so a forced pseudo-locale cannot appear as an option to a real user.
 */
export async function enablePseudoLocale(): Promise<boolean> {
  const forced = (globalThis as { __WQ_PSEUDO__?: boolean }).__WQ_PSEUDO__ === true
  if (!isDev() && !forced) return false

  // Straight off the generated catalogue, which is already note-free and prefix-free —
  // this used to re-run `toBundle` over the raw JSON to get to the same place.
  for (const [namespace, bundle] of Object.entries(CATALOGUE[FALLBACK_LOCALE] ?? {})) {
    const pseudoBundle = Object.fromEntries(
      Object.entries(bundle).map(([key, value]) => [key, pseudo(value)]),
    )
    i18n.addResourceBundle(PSEUDO_LOCALE, namespace, pseudoBundle, true, true)
  }

  // Awaited: `changeLanguage` resolves the new language, and a caller that renders
  // immediately after a fire-and-forget call sees the old one.
  await i18n.changeLanguage(PSEUDO_LOCALE)
  return true
}

export const currentLocale = (): Locale =>
  isSupported(i18n.language) ? i18n.language : FALLBACK_LOCALE
